// Vocabulary database: es = Spanish, en = English, nl = Dutch,
// ex = example phrase in Spanish, exEn/exNl = phrase translations.
// lv = CEFR level band. New words can simply be appended; ids must stay stable.
const VOCAB = [
  // ---------- A1 : greetings & basics ----------
  {id:"v001", lv:"A1", es:"hola", en:"hello", nl:"hallo", ex:"¡Hola! ¿Cómo estás?", exEn:"Hello! How are you?", exNl:"Hallo! Hoe gaat het met je?"},
  {id:"v002", lv:"A1", es:"adiós", en:"goodbye", nl:"tot ziens", ex:"Adiós, hasta mañana.", exEn:"Goodbye, see you tomorrow.", exNl:"Tot ziens, tot morgen."},
  {id:"v003", lv:"A1", es:"gracias", en:"thank you", nl:"dank je", ex:"Muchas gracias por todo.", exEn:"Thank you very much for everything.", exNl:"Heel erg bedankt voor alles."},
  {id:"v004", lv:"A1", es:"por favor", en:"please", nl:"alsjeblieft", ex:"Un café, por favor.", exEn:"A coffee, please.", exNl:"Een koffie, alsjeblieft."},
  {id:"v005", lv:"A1", es:"sí", en:"yes", nl:"ja", ex:"Sí, me gusta mucho.", exEn:"Yes, I like it a lot.", exNl:"Ja, ik vind het erg leuk."},
  {id:"v006", lv:"A1", es:"no", en:"no", nl:"nee", ex:"No, no quiero más.", exEn:"No, I don't want more.", exNl:"Nee, ik wil niet meer."},
  {id:"v007", lv:"A1", es:"perdón", en:"sorry / excuse me", nl:"sorry / pardon", ex:"Perdón, ¿dónde está el baño?", exEn:"Excuse me, where is the bathroom?", exNl:"Pardon, waar is het toilet?"},
  {id:"v008", lv:"A1", es:"buenos días", en:"good morning", nl:"goedemorgen", ex:"Buenos días, señora García.", exEn:"Good morning, Mrs. García.", exNl:"Goedemorgen, mevrouw García."},
  {id:"v009", lv:"A1", es:"buenas noches", en:"good night", nl:"goedenavond / welterusten", ex:"Buenas noches, hasta mañana.", exEn:"Good night, see you tomorrow.", exNl:"Welterusten, tot morgen."},
  {id:"v010", lv:"A1", es:"¿cómo estás?", en:"how are you?", nl:"hoe gaat het?", ex:"Hola Ana, ¿cómo estás?", exEn:"Hi Ana, how are you?", exNl:"Hoi Ana, hoe gaat het?"},
  {id:"v011", lv:"A1", es:"bien", en:"well / fine", nl:"goed", ex:"Estoy muy bien, gracias.", exEn:"I am very well, thanks.", exNl:"Het gaat heel goed, dank je."},
  {id:"v012", lv:"A1", es:"mal", en:"bad / badly", nl:"slecht", ex:"Hoy me siento mal.", exEn:"Today I feel bad.", exNl:"Vandaag voel ik me slecht."},
  {id:"v013", lv:"A1", es:"me llamo", en:"my name is", nl:"ik heet", ex:"Me llamo Sonja, ¿y tú?", exEn:"My name is Sonja, and you?", exNl:"Ik heet Sonja, en jij?"},
  {id:"v014", lv:"A1", es:"mucho gusto", en:"nice to meet you", nl:"aangenaam", ex:"Mucho gusto, Carlos.", exEn:"Nice to meet you, Carlos.", exNl:"Aangenaam, Carlos."},

  // ---------- A1 : people & family ----------
  {id:"v015", lv:"A1", es:"la familia", en:"the family", nl:"de familie", ex:"Mi familia es grande.", exEn:"My family is big.", exNl:"Mijn familie is groot."},
  {id:"v016", lv:"A1", es:"la madre", en:"the mother", nl:"de moeder", ex:"Mi madre se llama Rosa.", exEn:"My mother is called Rosa.", exNl:"Mijn moeder heet Rosa."},
  {id:"v017", lv:"A1", es:"el padre", en:"the father", nl:"de vader", ex:"Mi padre trabaja mucho.", exEn:"My father works a lot.", exNl:"Mijn vader werkt veel."},
  {id:"v018", lv:"A1", es:"el hermano", en:"the brother", nl:"de broer", ex:"Tengo un hermano mayor.", exEn:"I have an older brother.", exNl:"Ik heb een oudere broer."},
  {id:"v019", lv:"A1", es:"la hermana", en:"the sister", nl:"de zus", ex:"Mi hermana vive en Madrid.", exEn:"My sister lives in Madrid.", exNl:"Mijn zus woont in Madrid."},
  {id:"v020", lv:"A1", es:"el hijo", en:"the son", nl:"de zoon", ex:"Su hijo tiene cinco años.", exEn:"Her son is five years old.", exNl:"Haar zoon is vijf jaar oud."},
  {id:"v021", lv:"A1", es:"la hija", en:"the daughter", nl:"de dochter", ex:"Mi hija canta muy bien.", exEn:"My daughter sings very well.", exNl:"Mijn dochter zingt heel goed."},
  {id:"v022", lv:"A1", es:"el amigo", en:"the friend (m)", nl:"de vriend", ex:"Pablo es mi mejor amigo.", exEn:"Pablo is my best friend.", exNl:"Pablo is mijn beste vriend."},
  {id:"v023", lv:"A1", es:"la amiga", en:"the friend (f)", nl:"de vriendin", ex:"Voy al cine con mi amiga.", exEn:"I go to the cinema with my friend.", exNl:"Ik ga naar de bioscoop met mijn vriendin."},
  {id:"v024", lv:"A1", es:"el hombre", en:"the man", nl:"de man", ex:"Ese hombre es muy alto.", exEn:"That man is very tall.", exNl:"Die man is heel lang."},
  {id:"v025", lv:"A1", es:"la mujer", en:"the woman", nl:"de vrouw", ex:"La mujer lee un libro.", exEn:"The woman reads a book.", exNl:"De vrouw leest een boek."},
  {id:"v026", lv:"A1", es:"el niño", en:"the child / boy", nl:"het kind / de jongen", ex:"El niño juega en el parque.", exEn:"The boy plays in the park.", exNl:"De jongen speelt in het park."},

  // ---------- A1 : essential verbs ----------
  {id:"v027", lv:"A1", es:"ser", en:"to be (permanent)", nl:"zijn (blijvend)", ex:"Soy de Holanda.", exEn:"I am from Holland.", exNl:"Ik kom uit Nederland."},
  {id:"v028", lv:"A1", es:"estar", en:"to be (state/place)", nl:"zijn (toestand/plaats)", ex:"Estoy en casa.", exEn:"I am at home.", exNl:"Ik ben thuis."},
  {id:"v029", lv:"A1", es:"tener", en:"to have", nl:"hebben", ex:"Tengo dos gatos.", exEn:"I have two cats.", exNl:"Ik heb twee katten."},
  {id:"v030", lv:"A1", es:"ir", en:"to go", nl:"gaan", ex:"Voy al supermercado.", exEn:"I go to the supermarket.", exNl:"Ik ga naar de supermarkt."},
  {id:"v031", lv:"A1", es:"hacer", en:"to do / to make", nl:"doen / maken", ex:"¿Qué haces hoy?", exEn:"What are you doing today?", exNl:"Wat doe je vandaag?"},
  {id:"v032", lv:"A1", es:"querer", en:"to want / to love", nl:"willen / houden van", ex:"Quiero aprender español.", exEn:"I want to learn Spanish.", exNl:"Ik wil Spaans leren."},
  {id:"v033", lv:"A1", es:"comer", en:"to eat", nl:"eten", ex:"Comemos a las dos.", exEn:"We eat at two o'clock.", exNl:"We eten om twee uur."},
  {id:"v034", lv:"A1", es:"beber", en:"to drink", nl:"drinken", ex:"Bebo agua con la comida.", exEn:"I drink water with the meal.", exNl:"Ik drink water bij het eten."},
  {id:"v035", lv:"A1", es:"hablar", en:"to speak", nl:"spreken / praten", ex:"Hablo un poco de español.", exEn:"I speak a little Spanish.", exNl:"Ik spreek een beetje Spaans."},
  {id:"v036", lv:"A1", es:"vivir", en:"to live", nl:"wonen / leven", ex:"Vivo en una ciudad pequeña.", exEn:"I live in a small city.", exNl:"Ik woon in een kleine stad."},
  {id:"v037", lv:"A1", es:"trabajar", en:"to work", nl:"werken", ex:"Trabajo desde casa.", exEn:"I work from home.", exNl:"Ik werk vanuit huis."},
  {id:"v038", lv:"A1", es:"estudiar", en:"to study", nl:"studeren / leren", ex:"Estudio español cada día.", exEn:"I study Spanish every day.", exNl:"Ik leer elke dag Spaans."},
  {id:"v039", lv:"A1", es:"gustar", en:"to like (to please)", nl:"leuk vinden", ex:"Me gusta la música.", exEn:"I like music.", exNl:"Ik hou van muziek."},
  {id:"v040", lv:"A1", es:"ver", en:"to see / to watch", nl:"zien / kijken", ex:"Veo la televisión por la noche.", exEn:"I watch TV in the evening.", exNl:"Ik kijk 's avonds televisie."},
  {id:"v041", lv:"A1", es:"escuchar", en:"to listen", nl:"luisteren", ex:"Escucho canciones en español.", exEn:"I listen to songs in Spanish.", exNl:"Ik luister naar Spaanse liedjes."},
  {id:"v042", lv:"A1", es:"cantar", en:"to sing", nl:"zingen", ex:"Me gusta cantar en la ducha.", exEn:"I like singing in the shower.", exNl:"Ik zing graag onder de douche."},
  {id:"v043", lv:"A1", es:"bailar", en:"to dance", nl:"dansen", ex:"¿Quieres bailar conmigo?", exEn:"Do you want to dance with me?", exNl:"Wil je met me dansen?"},
  {id:"v044", lv:"A1", es:"dormir", en:"to sleep", nl:"slapen", ex:"Duermo ocho horas.", exEn:"I sleep eight hours.", exNl:"Ik slaap acht uur."},
  {id:"v045", lv:"A1", es:"comprar", en:"to buy", nl:"kopen", ex:"Compro pan en la panadería.", exEn:"I buy bread at the bakery.", exNl:"Ik koop brood bij de bakker."},

  // ---------- A1 : food & drink ----------
  {id:"v046", lv:"A1", es:"el agua", en:"the water", nl:"het water", ex:"Un vaso de agua, por favor.", exEn:"A glass of water, please.", exNl:"Een glas water, alsjeblieft."},
  {id:"v047", lv:"A1", es:"el café", en:"the coffee", nl:"de koffie", ex:"El café está caliente.", exEn:"The coffee is hot.", exNl:"De koffie is heet."},
  {id:"v048", lv:"A1", es:"el pan", en:"the bread", nl:"het brood", ex:"El pan está muy rico.", exEn:"The bread is very tasty.", exNl:"Het brood is erg lekker."},
  {id:"v049", lv:"A1", es:"la leche", en:"the milk", nl:"de melk", ex:"¿Quieres leche en el café?", exEn:"Do you want milk in the coffee?", exNl:"Wil je melk in de koffie?"},
  {id:"v050", lv:"A1", es:"la fruta", en:"the fruit", nl:"het fruit", ex:"Como fruta todos los días.", exEn:"I eat fruit every day.", exNl:"Ik eet elke dag fruit."},
  {id:"v051", lv:"A1", es:"la manzana", en:"the apple", nl:"de appel", ex:"La manzana es roja.", exEn:"The apple is red.", exNl:"De appel is rood."},
  {id:"v052", lv:"A1", es:"el queso", en:"the cheese", nl:"de kaas", ex:"El queso de Holanda es famoso.", exEn:"Cheese from Holland is famous.", exNl:"Kaas uit Nederland is beroemd."},
  {id:"v053", lv:"A1", es:"el pescado", en:"the fish (food)", nl:"de vis", ex:"Hoy comemos pescado.", exEn:"Today we eat fish.", exNl:"Vandaag eten we vis."},
  {id:"v054", lv:"A1", es:"la carne", en:"the meat", nl:"het vlees", ex:"No como mucha carne.", exEn:"I don't eat much meat.", exNl:"Ik eet niet veel vlees."},
  {id:"v055", lv:"A1", es:"el vino", en:"the wine", nl:"de wijn", ex:"Una copa de vino tinto.", exEn:"A glass of red wine.", exNl:"Een glas rode wijn."},
  {id:"v056", lv:"A1", es:"la cerveza", en:"the beer", nl:"het bier", ex:"Una cerveza fría, por favor.", exEn:"A cold beer, please.", exNl:"Een koud biertje, alsjeblieft."},
  {id:"v057", lv:"A1", es:"el desayuno", en:"the breakfast", nl:"het ontbijt", ex:"El desayuno es a las ocho.", exEn:"Breakfast is at eight.", exNl:"Het ontbijt is om acht uur."},
  {id:"v058", lv:"A1", es:"la cena", en:"the dinner", nl:"het avondeten", ex:"La cena está lista.", exEn:"Dinner is ready.", exNl:"Het avondeten is klaar."},

  // ---------- A1 : places & things ----------
  {id:"v059", lv:"A1", es:"la casa", en:"the house", nl:"het huis", ex:"Mi casa tiene un jardín.", exEn:"My house has a garden.", exNl:"Mijn huis heeft een tuin."},
  {id:"v060", lv:"A1", es:"la ciudad", en:"the city", nl:"de stad", ex:"La ciudad es muy bonita.", exEn:"The city is very pretty.", exNl:"De stad is erg mooi."},
  {id:"v061", lv:"A1", es:"la calle", en:"the street", nl:"de straat", ex:"Vivo en esta calle.", exEn:"I live on this street.", exNl:"Ik woon in deze straat."},
  {id:"v062", lv:"A1", es:"la playa", en:"the beach", nl:"het strand", ex:"En verano voy a la playa.", exEn:"In summer I go to the beach.", exNl:"In de zomer ga ik naar het strand."},
  {id:"v063", lv:"A1", es:"la tienda", en:"the shop", nl:"de winkel", ex:"La tienda abre a las diez.", exEn:"The shop opens at ten.", exNl:"De winkel gaat om tien uur open."},
  {id:"v064", lv:"A1", es:"la escuela", en:"the school", nl:"de school", ex:"Los niños van a la escuela.", exEn:"The children go to school.", exNl:"De kinderen gaan naar school."},
  {id:"v065", lv:"A1", es:"el trabajo", en:"the work / job", nl:"het werk", ex:"Voy al trabajo en bici.", exEn:"I go to work by bike.", exNl:"Ik ga op de fiets naar mijn werk."},
  {id:"v066", lv:"A1", es:"el libro", en:"the book", nl:"het boek", ex:"Leo un libro interesante.", exEn:"I'm reading an interesting book.", exNl:"Ik lees een interessant boek."},
  {id:"v067", lv:"A1", es:"la mesa", en:"the table", nl:"de tafel", ex:"El libro está en la mesa.", exEn:"The book is on the table.", exNl:"Het boek ligt op de tafel."},
  {id:"v068", lv:"A1", es:"la puerta", en:"the door", nl:"de deur", ex:"La puerta está abierta.", exEn:"The door is open.", exNl:"De deur is open."},
  {id:"v069", lv:"A1", es:"la ventana", en:"the window", nl:"het raam", ex:"Abro la ventana.", exEn:"I open the window.", exNl:"Ik doe het raam open."},
  {id:"v070", lv:"A1", es:"el coche", en:"the car", nl:"de auto", ex:"El coche es azul.", exEn:"The car is blue.", exNl:"De auto is blauw."},
  {id:"v071", lv:"A1", es:"el perro", en:"the dog", nl:"de hond", ex:"Mi perro se llama Toby.", exEn:"My dog is called Toby.", exNl:"Mijn hond heet Toby."},
  {id:"v072", lv:"A1", es:"el gato", en:"the cat", nl:"de kat", ex:"El gato duerme en el sofá.", exEn:"The cat sleeps on the sofa.", exNl:"De kat slaapt op de bank."},
  {id:"v073", lv:"A1", es:"el dinero", en:"the money", nl:"het geld", ex:"No tengo mucho dinero.", exEn:"I don't have much money.", exNl:"Ik heb niet veel geld."},

  // ---------- A1 : time & numbers ----------
  {id:"v074", lv:"A1", es:"hoy", en:"today", nl:"vandaag", ex:"Hoy hace buen tiempo.", exEn:"Today the weather is nice.", exNl:"Vandaag is het mooi weer."},
  {id:"v075", lv:"A1", es:"mañana", en:"tomorrow / morning", nl:"morgen / ochtend", ex:"Mañana es sábado.", exEn:"Tomorrow is Saturday.", exNl:"Morgen is het zaterdag."},
  {id:"v076", lv:"A1", es:"ayer", en:"yesterday", nl:"gisteren", ex:"Ayer fue lunes.", exEn:"Yesterday was Monday.", exNl:"Gisteren was het maandag."},
  {id:"v077", lv:"A1", es:"ahora", en:"now", nl:"nu", ex:"Ahora estoy ocupada.", exEn:"I'm busy right now.", exNl:"Ik ben nu bezig."},
  {id:"v078", lv:"A1", es:"siempre", en:"always", nl:"altijd", ex:"Siempre desayuno café.", exEn:"I always have coffee for breakfast.", exNl:"Ik drink altijd koffie bij het ontbijt."},
  {id:"v079", lv:"A1", es:"nunca", en:"never", nl:"nooit", ex:"Nunca llego tarde.", exEn:"I never arrive late.", exNl:"Ik kom nooit te laat."},
  {id:"v080", lv:"A1", es:"la semana", en:"the week", nl:"de week", ex:"La semana tiene siete días.", exEn:"The week has seven days.", exNl:"De week heeft zeven dagen."},
  {id:"v081", lv:"A1", es:"el día", en:"the day", nl:"de dag", ex:"¡Qué día tan bonito!", exEn:"What a beautiful day!", exNl:"Wat een mooie dag!"},
  {id:"v082", lv:"A1", es:"la noche", en:"the night", nl:"de nacht / avond", ex:"Por la noche leo un poco.", exEn:"At night I read a little.", exNl:"'s Avonds lees ik een beetje."},
  {id:"v083", lv:"A1", es:"la hora", en:"the hour / time", nl:"het uur / de tijd", ex:"¿Qué hora es?", exEn:"What time is it?", exNl:"Hoe laat is het?"},
  {id:"v084", lv:"A1", es:"el año", en:"the year", nl:"het jaar", ex:"Este año viajo a España.", exEn:"This year I travel to Spain.", exNl:"Dit jaar reis ik naar Spanje."},

  // ---------- A1 : adjectives & misc ----------
  {id:"v085", lv:"A1", es:"grande", en:"big", nl:"groot", ex:"Madrid es una ciudad grande.", exEn:"Madrid is a big city.", exNl:"Madrid is een grote stad."},
  {id:"v086", lv:"A1", es:"pequeño", en:"small", nl:"klein", ex:"El pueblo es pequeño.", exEn:"The village is small.", exNl:"Het dorp is klein."},
  {id:"v087", lv:"A1", es:"bueno", en:"good", nl:"goed", ex:"Es un restaurante muy bueno.", exEn:"It's a very good restaurant.", exNl:"Het is een heel goed restaurant."},
  {id:"v088", lv:"A1", es:"nuevo", en:"new", nl:"nieuw", ex:"Tengo un teléfono nuevo.", exEn:"I have a new phone.", exNl:"Ik heb een nieuwe telefoon."},
  {id:"v089", lv:"A1", es:"bonito", en:"pretty / nice", nl:"mooi", ex:"¡Qué vestido tan bonito!", exEn:"What a pretty dress!", exNl:"Wat een mooie jurk!"},
  {id:"v090", lv:"A1", es:"feliz", en:"happy", nl:"gelukkig / blij", ex:"Estoy muy feliz hoy.", exEn:"I am very happy today.", exNl:"Ik ben vandaag heel blij."},
  {id:"v091", lv:"A1", es:"cansado", en:"tired", nl:"moe", ex:"Estoy cansada después del trabajo.", exEn:"I am tired after work.", exNl:"Ik ben moe na het werk."},
  {id:"v092", lv:"A1", es:"caliente", en:"hot (temperature)", nl:"heet / warm", ex:"La sopa está caliente.", exEn:"The soup is hot.", exNl:"De soep is heet."},
  {id:"v093", lv:"A1", es:"frío", en:"cold", nl:"koud", ex:"El agua está fría.", exEn:"The water is cold.", exNl:"Het water is koud."},
  {id:"v094", lv:"A1", es:"mucho", en:"a lot / much", nl:"veel", ex:"Trabajo mucho esta semana.", exEn:"I work a lot this week.", exNl:"Ik werk veel deze week."},
  {id:"v095", lv:"A1", es:"poco", en:"little / few", nl:"weinig", ex:"Hablo un poco de español.", exEn:"I speak a little Spanish.", exNl:"Ik spreek een beetje Spaans."},
  {id:"v096", lv:"A1", es:"aquí", en:"here", nl:"hier", ex:"Vivo aquí desde marzo.", exEn:"I live here since March.", exNl:"Ik woon hier sinds maart."},
  {id:"v097", lv:"A1", es:"¿dónde?", en:"where?", nl:"waar?", ex:"¿Dónde está la estación?", exEn:"Where is the station?", exNl:"Waar is het station?"},
  {id:"v098", lv:"A1", es:"¿cuánto?", en:"how much?", nl:"hoeveel?", ex:"¿Cuánto cuesta esto?", exEn:"How much does this cost?", exNl:"Hoeveel kost dit?"},
  {id:"v099", lv:"A1", es:"el sol", en:"the sun", nl:"de zon", ex:"Hoy hay mucho sol.", exEn:"Today there's a lot of sun.", exNl:"Vandaag is er veel zon."},
  {id:"v100", lv:"A1", es:"la lluvia", en:"the rain", nl:"de regen", ex:"No me gusta la lluvia.", exEn:"I don't like the rain.", exNl:"Ik hou niet van regen."},

  // ---------- A2 : daily life & routines ----------
  {id:"v101", lv:"A2", es:"levantarse", en:"to get up", nl:"opstaan", ex:"Me levanto a las siete.", exEn:"I get up at seven.", exNl:"Ik sta om zeven uur op."},
  {id:"v102", lv:"A2", es:"ducharse", en:"to shower", nl:"douchen", ex:"Me ducho por la mañana.", exEn:"I shower in the morning.", exNl:"Ik douche 's ochtends."},
  {id:"v103", lv:"A2", es:"desayunar", en:"to have breakfast", nl:"ontbijten", ex:"Desayuno con mi familia.", exEn:"I have breakfast with my family.", exNl:"Ik ontbijt met mijn gezin."},
  {id:"v104", lv:"A2", es:"empezar", en:"to begin", nl:"beginnen", ex:"La clase empieza a las nueve.", exEn:"The class begins at nine.", exNl:"De les begint om negen uur."},
  {id:"v105", lv:"A2", es:"terminar", en:"to finish", nl:"eindigen / afmaken", ex:"Termino de trabajar a las seis.", exEn:"I finish working at six.", exNl:"Ik ben om zes uur klaar met werken."},
  {id:"v106", lv:"A2", es:"ayudar", en:"to help", nl:"helpen", ex:"¿Me puedes ayudar?", exEn:"Can you help me?", exNl:"Kun je me helpen?"},
  {id:"v107", lv:"A2", es:"buscar", en:"to look for", nl:"zoeken", ex:"Busco mis llaves.", exEn:"I'm looking for my keys.", exNl:"Ik zoek mijn sleutels."},
  {id:"v108", lv:"A2", es:"encontrar", en:"to find", nl:"vinden", ex:"No encuentro mi teléfono.", exEn:"I can't find my phone.", exNl:"Ik kan mijn telefoon niet vinden."},
  {id:"v109", lv:"A2", es:"llegar", en:"to arrive", nl:"aankomen", ex:"El tren llega a las cinco.", exEn:"The train arrives at five.", exNl:"De trein komt om vijf uur aan."},
  {id:"v110", lv:"A2", es:"salir", en:"to go out / leave", nl:"uitgaan / vertrekken", ex:"Salgo con amigos el viernes.", exEn:"I go out with friends on Friday.", exNl:"Ik ga vrijdag uit met vrienden."},
  {id:"v111", lv:"A2", es:"volver", en:"to return", nl:"terugkomen", ex:"Vuelvo a casa a las ocho.", exEn:"I return home at eight.", exNl:"Ik kom om acht uur thuis."},
  {id:"v112", lv:"A2", es:"pensar", en:"to think", nl:"denken", ex:"Pienso mucho en ti.", exEn:"I think about you a lot.", exNl:"Ik denk veel aan je."},
  {id:"v113", lv:"A2", es:"saber", en:"to know (facts)", nl:"weten", ex:"No sé la respuesta.", exEn:"I don't know the answer.", exNl:"Ik weet het antwoord niet."},
  {id:"v114", lv:"A2", es:"conocer", en:"to know (people/places)", nl:"kennen", ex:"¿Conoces Barcelona?", exEn:"Do you know Barcelona?", exNl:"Ken je Barcelona?"},
  {id:"v115", lv:"A2", es:"necesitar", en:"to need", nl:"nodig hebben", ex:"Necesito unas vacaciones.", exEn:"I need a vacation.", exNl:"Ik heb vakantie nodig."},
  {id:"v116", lv:"A2", es:"llevar", en:"to carry / to wear", nl:"dragen / meenemen", ex:"Llevo una chaqueta roja.", exEn:"I'm wearing a red jacket.", exNl:"Ik draag een rode jas."},
  {id:"v117", lv:"A2", es:"pagar", en:"to pay", nl:"betalen", ex:"¿Puedo pagar con tarjeta?", exEn:"Can I pay by card?", exNl:"Kan ik met kaart betalen?"},
  {id:"v118", lv:"A2", es:"abrir", en:"to open", nl:"openen", ex:"El museo abre a las diez.", exEn:"The museum opens at ten.", exNl:"Het museum opent om tien uur."},
  {id:"v119", lv:"A2", es:"cerrar", en:"to close", nl:"sluiten", ex:"Cierran la tienda a las nueve.", exEn:"They close the shop at nine.", exNl:"Ze sluiten de winkel om negen uur."},
  {id:"v120", lv:"A2", es:"esperar", en:"to wait / to hope", nl:"wachten / hopen", ex:"Espero el autobús.", exEn:"I'm waiting for the bus.", exNl:"Ik wacht op de bus."},

  // ---------- A2 : travel & city ----------
  {id:"v121", lv:"A2", es:"el viaje", en:"the trip", nl:"de reis", ex:"El viaje dura tres horas.", exEn:"The trip takes three hours.", exNl:"De reis duurt drie uur."},
  {id:"v122", lv:"A2", es:"el aeropuerto", en:"the airport", nl:"het vliegveld", ex:"Vamos al aeropuerto en taxi.", exEn:"We go to the airport by taxi.", exNl:"We gaan met de taxi naar het vliegveld."},
  {id:"v123", lv:"A2", es:"el billete", en:"the ticket", nl:"het kaartje / ticket", ex:"Compro un billete de tren.", exEn:"I buy a train ticket.", exNl:"Ik koop een treinkaartje."},
  {id:"v124", lv:"A2", es:"la maleta", en:"the suitcase", nl:"de koffer", ex:"Mi maleta pesa mucho.", exEn:"My suitcase weighs a lot.", exNl:"Mijn koffer is erg zwaar."},
  {id:"v125", lv:"A2", es:"el hotel", en:"the hotel", nl:"het hotel", ex:"El hotel está cerca de la playa.", exEn:"The hotel is near the beach.", exNl:"Het hotel is dicht bij het strand."},
  {id:"v126", lv:"A2", es:"la habitación", en:"the room", nl:"de kamer", ex:"La habitación tiene vistas al mar.", exEn:"The room has a sea view.", exNl:"De kamer heeft uitzicht op zee."},
  {id:"v127", lv:"A2", es:"a la derecha", en:"to the right", nl:"naar rechts", ex:"El banco está a la derecha.", exEn:"The bank is on the right.", exNl:"De bank is aan de rechterkant."},
  {id:"v128", lv:"A2", es:"a la izquierda", en:"to the left", nl:"naar links", ex:"Gira a la izquierda en la plaza.", exEn:"Turn left at the square.", exNl:"Sla linksaf bij het plein."},
  {id:"v129", lv:"A2", es:"cerca", en:"near", nl:"dichtbij", ex:"La farmacia está cerca.", exEn:"The pharmacy is nearby.", exNl:"De apotheek is dichtbij."},
  {id:"v130", lv:"A2", es:"lejos", en:"far", nl:"ver weg", ex:"El centro no está lejos.", exEn:"The center is not far.", exNl:"Het centrum is niet ver."},
  {id:"v131", lv:"A2", es:"el mar", en:"the sea", nl:"de zee", ex:"Me encanta nadar en el mar.", exEn:"I love swimming in the sea.", exNl:"Ik zwem heel graag in de zee."},
  {id:"v132", lv:"A2", es:"la montaña", en:"the mountain", nl:"de berg", ex:"En invierno vamos a la montaña.", exEn:"In winter we go to the mountains.", exNl:"In de winter gaan we naar de bergen."},
  {id:"v133", lv:"A2", es:"el extranjero", en:"abroad / foreigner", nl:"het buitenland / buitenlander", ex:"Me gusta viajar al extranjero.", exEn:"I like traveling abroad.", exNl:"Ik reis graag naar het buitenland."},

  // ---------- A2 : feelings & descriptions ----------
  {id:"v134", lv:"A2", es:"contento", en:"glad / pleased", nl:"tevreden / blij", ex:"Estoy contenta con mi progreso.", exEn:"I am pleased with my progress.", exNl:"Ik ben blij met mijn vooruitgang."},
  {id:"v135", lv:"A2", es:"triste", en:"sad", nl:"verdrietig", ex:"La película es un poco triste.", exEn:"The movie is a bit sad.", exNl:"De film is een beetje verdrietig."},
  {id:"v136", lv:"A2", es:"nervioso", en:"nervous", nl:"nerveus", ex:"Estoy nerviosa por el examen.", exEn:"I'm nervous about the exam.", exNl:"Ik ben nerveus voor het examen."},
  {id:"v137", lv:"A2", es:"tranquilo", en:"calm / quiet", nl:"rustig", ex:"Es un barrio muy tranquilo.", exEn:"It's a very quiet neighborhood.", exNl:"Het is een heel rustige buurt."},
  {id:"v138", lv:"A2", es:"enfermo", en:"sick / ill", nl:"ziek", ex:"Hoy no voy, estoy enferma.", exEn:"I'm not going today, I'm sick.", exNl:"Ik ga vandaag niet, ik ben ziek."},
  {id:"v139", lv:"A2", es:"divertido", en:"fun / funny", nl:"leuk / grappig", ex:"La fiesta fue muy divertida.", exEn:"The party was a lot of fun.", exNl:"Het feest was heel leuk."},
  {id:"v140", lv:"A2", es:"aburrido", en:"boring / bored", nl:"saai / verveeld", ex:"El programa es aburrido.", exEn:"The show is boring.", exNl:"Het programma is saai."},
  {id:"v141", lv:"A2", es:"fácil", en:"easy", nl:"makkelijk", ex:"Esta lección es fácil.", exEn:"This lesson is easy.", exNl:"Deze les is makkelijk."},
  {id:"v142", lv:"A2", es:"difícil", en:"difficult", nl:"moeilijk", ex:"El español no es tan difícil.", exEn:"Spanish is not that difficult.", exNl:"Spaans is niet zo moeilijk."},
  {id:"v143", lv:"A2", es:"importante", en:"important", nl:"belangrijk", ex:"Es importante practicar cada día.", exEn:"It's important to practice every day.", exNl:"Het is belangrijk om elke dag te oefenen."},
  {id:"v144", lv:"A2", es:"el tiempo", en:"the time / weather", nl:"de tijd / het weer", ex:"No tengo tiempo hoy.", exEn:"I don't have time today.", exNl:"Ik heb vandaag geen tijd."},
  {id:"v145", lv:"A2", es:"la salud", en:"the health", nl:"de gezondheid", ex:"La salud es lo más importante.", exEn:"Health is the most important thing.", exNl:"Gezondheid is het allerbelangrijkste."},
  {id:"v146", lv:"A2", es:"el cuerpo", en:"the body", nl:"het lichaam", ex:"El deporte es bueno para el cuerpo.", exEn:"Sport is good for the body.", exNl:"Sport is goed voor het lichaam."},
  {id:"v147", lv:"A2", es:"la cabeza", en:"the head", nl:"het hoofd", ex:"Me duele la cabeza.", exEn:"My head hurts.", exNl:"Ik heb hoofdpijn."},
  {id:"v148", lv:"A2", es:"el corazón", en:"the heart", nl:"het hart", ex:"Te quiero con todo mi corazón.", exEn:"I love you with all my heart.", exNl:"Ik hou van je met heel mijn hart."},

  // ---------- A2 : useful phrases & connectors ----------
  {id:"v149", lv:"A2", es:"porque", en:"because", nl:"omdat", ex:"Estudio español porque me gusta.", exEn:"I study Spanish because I like it.", exNl:"Ik leer Spaans omdat ik het leuk vind."},
  {id:"v150", lv:"A2", es:"pero", en:"but", nl:"maar", ex:"Quiero ir, pero estoy cansada.", exEn:"I want to go, but I'm tired.", exNl:"Ik wil gaan, maar ik ben moe."},
  {id:"v151", lv:"A2", es:"también", en:"also", nl:"ook", ex:"Yo también hablo inglés.", exEn:"I also speak English.", exNl:"Ik spreek ook Engels."},
  {id:"v152", lv:"A2", es:"entonces", en:"then / so", nl:"dan / dus", ex:"Entonces, ¿nos vemos mañana?", exEn:"So, shall we meet tomorrow?", exNl:"Dus, zien we elkaar morgen?"},
  {id:"v153", lv:"A2", es:"a veces", en:"sometimes", nl:"soms", ex:"A veces cocino paella.", exEn:"Sometimes I cook paella.", exNl:"Soms kook ik paella."},
  {id:"v154", lv:"A2", es:"casi", en:"almost", nl:"bijna", ex:"Casi siempre tengo razón.", exEn:"I'm almost always right.", exNl:"Ik heb bijna altijd gelijk."},
  {id:"v155", lv:"A2", es:"todavía", en:"still / yet", nl:"nog / nog steeds", ex:"Todavía no he comido.", exEn:"I haven't eaten yet.", exNl:"Ik heb nog niet gegeten."},
  {id:"v156", lv:"A2", es:"demasiado", en:"too much", nl:"te veel", ex:"El café está demasiado caliente.", exEn:"The coffee is too hot.", exNl:"De koffie is te heet."},
  {id:"v157", lv:"A2", es:"quizás", en:"maybe", nl:"misschien", ex:"Quizás vamos al cine.", exEn:"Maybe we'll go to the cinema.", exNl:"Misschien gaan we naar de bioscoop."},
  {id:"v158", lv:"A2", es:"claro", en:"of course / clear", nl:"natuurlijk / duidelijk", ex:"¡Claro que sí!", exEn:"Of course!", exNl:"Natuurlijk!"},
  {id:"v159", lv:"A2", es:"la vez", en:"the time (occasion)", nl:"de keer", ex:"Es mi primera vez en España.", exEn:"It's my first time in Spain.", exNl:"Het is mijn eerste keer in Spanje."},
  {id:"v160", lv:"A2", es:"el fin de semana", en:"the weekend", nl:"het weekend", ex:"El fin de semana descanso.", exEn:"On the weekend I rest.", exNl:"In het weekend rust ik uit."},
  {id:"v161", lv:"A2", es:"las vacaciones", en:"the holidays", nl:"de vakantie", ex:"Las vacaciones empiezan en julio.", exEn:"The holidays start in July.", exNl:"De vakantie begint in juli."},
  {id:"v162", lv:"A2", es:"la cita", en:"the appointment / date", nl:"de afspraak", ex:"Tengo una cita con el médico.", exEn:"I have a doctor's appointment.", exNl:"Ik heb een afspraak bij de dokter."},
  {id:"v163", lv:"A2", es:"la pregunta", en:"the question", nl:"de vraag", ex:"Tengo una pregunta importante.", exEn:"I have an important question.", exNl:"Ik heb een belangrijke vraag."},
  {id:"v164", lv:"A2", es:"la respuesta", en:"the answer", nl:"het antwoord", ex:"La respuesta es correcta.", exEn:"The answer is correct.", exNl:"Het antwoord is juist."},
  {id:"v165", lv:"A2", es:"la palabra", en:"the word", nl:"het woord", ex:"Aprendo diez palabras al día.", exEn:"I learn ten words a day.", exNl:"Ik leer tien woorden per dag."},
  {id:"v166", lv:"A2", es:"la canción", en:"the song", nl:"het liedje", ex:"Esta canción me encanta.", exEn:"I love this song.", exNl:"Ik ben dol op dit liedje."},
  {id:"v167", lv:"A2", es:"jugar", en:"to play (games/sport)", nl:"spelen", ex:"Los sábados juego al tenis.", exEn:"On Saturdays I play tennis.", exNl:"Op zaterdag speel ik tennis."},
  {id:"v168", lv:"A2", es:"llover", en:"to rain", nl:"regenen", ex:"En Holanda llueve mucho.", exEn:"In Holland it rains a lot.", exNl:"In Nederland regent het veel."},
  {id:"v169", lv:"A2", es:"recordar", en:"to remember", nl:"herinneren / onthouden", ex:"No recuerdo su nombre.", exEn:"I don't remember his name.", exNl:"Ik weet zijn naam niet meer."},
  {id:"v170", lv:"A2", es:"olvidar", en:"to forget", nl:"vergeten", ex:"Siempre olvido las llaves.", exEn:"I always forget my keys.", exNl:"Ik vergeet altijd mijn sleutels."},

  // ---------- B1 : opinions & experiences ----------
  {id:"v171", lv:"B1", es:"la experiencia", en:"the experience", nl:"de ervaring", ex:"Fue una experiencia inolvidable.", exEn:"It was an unforgettable experience.", exNl:"Het was een onvergetelijke ervaring."},
  {id:"v172", lv:"B1", es:"la opinión", en:"the opinion", nl:"de mening", ex:"En mi opinión, tienes razón.", exEn:"In my opinion, you are right.", exNl:"Naar mijn mening heb je gelijk."},
  {id:"v173", lv:"B1", es:"opinar", en:"to think / give an opinion", nl:"vinden / menen", ex:"¿Qué opinas de esta idea?", exEn:"What do you think of this idea?", exNl:"Wat vind je van dit idee?"},
  {id:"v174", lv:"B1", es:"estar de acuerdo", en:"to agree", nl:"het eens zijn", ex:"Estoy de acuerdo contigo.", exEn:"I agree with you.", exNl:"Ik ben het met je eens."},
  {id:"v175", lv:"B1", es:"aunque", en:"although", nl:"hoewel", ex:"Aunque llueve, salimos.", exEn:"Although it's raining, we go out.", exNl:"Hoewel het regent, gaan we naar buiten."},
  {id:"v176", lv:"B1", es:"sin embargo", en:"however", nl:"echter / toch", ex:"Es caro; sin embargo, lo compro.", exEn:"It's expensive; however, I'll buy it.", exNl:"Het is duur; toch koop ik het."},
  {id:"v177", lv:"B1", es:"además", en:"besides / moreover", nl:"bovendien", ex:"Además, el hotel incluye desayuno.", exEn:"Moreover, the hotel includes breakfast.", exNl:"Bovendien is het ontbijt bij het hotel inbegrepen."},
  {id:"v178", lv:"B1", es:"por eso", en:"that's why", nl:"daarom", ex:"Me encanta la música; por eso canto.", exEn:"I love music; that's why I sing.", exNl:"Ik hou van muziek; daarom zing ik."},
  {id:"v179", lv:"B1", es:"mientras", en:"while", nl:"terwijl", ex:"Escucho música mientras cocino.", exEn:"I listen to music while I cook.", exNl:"Ik luister naar muziek terwijl ik kook."},
  {id:"v180", lv:"B1", es:"desde hace", en:"since / for (time)", nl:"sinds / al (tijd)", ex:"Estudio español desde hace un año.", exEn:"I've been studying Spanish for a year.", exNl:"Ik leer al een jaar Spaans."},

  // ---------- B1 : richer verbs ----------
  {id:"v181", lv:"B1", es:"conseguir", en:"to achieve / to get", nl:"bereiken / krijgen", ex:"Conseguí un trabajo nuevo.", exEn:"I got a new job.", exNl:"Ik heb een nieuwe baan gekregen."},
  {id:"v182", lv:"B1", es:"intentar", en:"to try", nl:"proberen", ex:"Intento hablar solo en español.", exEn:"I try to speak only in Spanish.", exNl:"Ik probeer alleen Spaans te spreken."},
  {id:"v183", lv:"B1", es:"lograr", en:"to manage / accomplish", nl:"slagen in / bereiken", ex:"Logré terminar el curso.", exEn:"I managed to finish the course.", exNl:"Het is me gelukt de cursus af te maken."},
  {id:"v184", lv:"B1", es:"mejorar", en:"to improve", nl:"verbeteren", ex:"Quiero mejorar mi pronunciación.", exEn:"I want to improve my pronunciation.", exNl:"Ik wil mijn uitspraak verbeteren."},
  {id:"v185", lv:"B1", es:"desarrollar", en:"to develop", nl:"ontwikkelen", ex:"La empresa desarrolla aplicaciones.", exEn:"The company develops applications.", exNl:"Het bedrijf ontwikkelt applicaties."},
  {id:"v186", lv:"B1", es:"aprovechar", en:"to make the most of", nl:"benutten / profiteren van", ex:"Aprovecho el viaje para practicar.", exEn:"I use the trip to practice.", exNl:"Ik benut de reis om te oefenen."},
  {id:"v187", lv:"B1", es:"darse cuenta", en:"to realize", nl:"beseffen", ex:"Me di cuenta de mi error.", exEn:"I realized my mistake.", exNl:"Ik besefte mijn fout."},
  {id:"v188", lv:"B1", es:"soler", en:"to usually do", nl:"gewoonlijk doen", ex:"Suelo pasear después de cenar.", exEn:"I usually take a walk after dinner.", exNl:"Ik maak meestal een wandeling na het eten."},
  {id:"v189", lv:"B1", es:"echar de menos", en:"to miss (someone)", nl:"missen (iemand)", ex:"Echo de menos a mi familia.", exEn:"I miss my family.", exNl:"Ik mis mijn familie."},
  {id:"v190", lv:"B1", es:"tener ganas de", en:"to feel like", nl:"zin hebben in", ex:"Tengo ganas de viajar.", exEn:"I feel like traveling.", exNl:"Ik heb zin om te reizen."},
  {id:"v191", lv:"B1", es:"quejarse", en:"to complain", nl:"klagen", ex:"Se queja del ruido.", exEn:"He complains about the noise.", exNl:"Hij klaagt over het lawaai."},
  {id:"v192", lv:"B1", es:"proponer", en:"to propose / suggest", nl:"voorstellen", ex:"Propongo ir a la playa.", exEn:"I suggest going to the beach.", exNl:"Ik stel voor om naar het strand te gaan."},
  {id:"v193", lv:"B1", es:"elegir", en:"to choose", nl:"kiezen", ex:"Es difícil elegir un plato.", exEn:"It's hard to choose a dish.", exNl:"Het is moeilijk om een gerecht te kiezen."},
  {id:"v194", lv:"B1", es:"aconsejar", en:"to advise", nl:"adviseren", ex:"Te aconsejo descansar más.", exEn:"I advise you to rest more.", exNl:"Ik raad je aan meer te rusten."},

  // ---------- B1 : society & abstract ----------
  {id:"v195", lv:"B1", es:"el medio ambiente", en:"the environment", nl:"het milieu", ex:"Cuidar el medio ambiente es urgente.", exEn:"Taking care of the environment is urgent.", exNl:"Zorgen voor het milieu is dringend."},
  {id:"v196", lv:"B1", es:"la noticia", en:"the news (item)", nl:"het nieuws(bericht)", ex:"¿Has leído la noticia de hoy?", exEn:"Have you read today's news?", exNl:"Heb je het nieuws van vandaag gelezen?"},
  {id:"v197", lv:"B1", es:"la costumbre", en:"the custom / habit", nl:"de gewoonte", ex:"Es una costumbre española.", exEn:"It's a Spanish custom.", exNl:"Het is een Spaanse gewoonte."},
  {id:"v198", lv:"B1", es:"el comportamiento", en:"the behavior", nl:"het gedrag", ex:"Su comportamiento fue extraño.", exEn:"His behavior was strange.", exNl:"Zijn gedrag was vreemd."},
  {id:"v199", lv:"B1", es:"la ventaja", en:"the advantage", nl:"het voordeel", ex:"Vivir cerca tiene muchas ventajas.", exEn:"Living nearby has many advantages.", exNl:"Dichtbij wonen heeft veel voordelen."},
  {id:"v200", lv:"B1", es:"la desventaja", en:"the disadvantage", nl:"het nadeel", ex:"La desventaja es el precio.", exEn:"The disadvantage is the price.", exNl:"Het nadeel is de prijs."},
  {id:"v201", lv:"B1", es:"el nivel", en:"the level", nl:"het niveau", ex:"Mi nivel de español sube.", exEn:"My level of Spanish is rising.", exNl:"Mijn niveau Spaans stijgt."},
  {id:"v202", lv:"B1", es:"la meta", en:"the goal", nl:"het doel", ex:"Mi meta es llegar al nivel B1.", exEn:"My goal is to reach level B1.", exNl:"Mijn doel is niveau B1 te halen."},
  {id:"v203", lv:"B1", es:"el esfuerzo", en:"the effort", nl:"de inspanning / moeite", ex:"Con esfuerzo todo es posible.", exEn:"With effort everything is possible.", exNl:"Met inspanning is alles mogelijk."},
  {id:"v204", lv:"B1", es:"la confianza", en:"the confidence / trust", nl:"het vertrouwen", ex:"Hablar da confianza.", exEn:"Speaking gives confidence.", exNl:"Spreken geeft zelfvertrouwen."},
  {id:"v205", lv:"B1", es:"el recuerdo", en:"the memory (of something)", nl:"de herinnering", ex:"Tengo buenos recuerdos de ese verano.", exEn:"I have good memories of that summer.", exNl:"Ik heb goede herinneringen aan die zomer."},
  {id:"v206", lv:"B1", es:"la esperanza", en:"the hope", nl:"de hoop", ex:"Nunca pierdas la esperanza.", exEn:"Never lose hope.", exNl:"Verlies nooit de hoop."},
  {id:"v207", lv:"B1", es:"el consejo", en:"the advice", nl:"het advies", ex:"Gracias por tu consejo.", exEn:"Thanks for your advice.", exNl:"Bedankt voor je advies."},
  {id:"v208", lv:"B1", es:"la mentira", en:"the lie", nl:"de leugen", ex:"Eso es una mentira.", exEn:"That is a lie.", exNl:"Dat is een leugen."},
  {id:"v209", lv:"B1", es:"la verdad", en:"the truth", nl:"de waarheid", ex:"Siempre digo la verdad.", exEn:"I always tell the truth.", exNl:"Ik zeg altijd de waarheid."},
  {id:"v210", lv:"B1", es:"tener éxito", en:"to be successful", nl:"succes hebben", ex:"Su restaurante tiene mucho éxito.", exEn:"Her restaurant is very successful.", exNl:"Haar restaurant is erg succesvol."}
];
