// Hands-free speaking drills — graded A1→B2, organised by topic.
// ~100 sentences per level across 10 topics. es = target, en = meaning.
const TALK_TOPICS = [
  { key: "greetings", label: "Greetings & intros", icon: "👋" },
  { key: "family",    label: "Family & people",    icon: "👨‍👩‍👧" },
  { key: "food",      label: "Food & eating out",  icon: "🍽️" },
  { key: "shopping",  label: "Shopping & money",   icon: "🛒" },
  { key: "travel",    label: "Travel & directions", icon: "✈️" },
  { key: "routine",   label: "Daily routine & time", icon: "⏰" },
  { key: "health",    label: "Health & body",      icon: "🩺" },
  { key: "work",      label: "Work & studies",     icon: "💼" },
  { key: "weather",   label: "Weather & nature",   icon: "☀️" },
  { key: "social",    label: "Feelings & plans",   icon: "💬" }
];

const DRILLS = [
  /* ===================== A1 ===================== */
  // greetings
  {id:"dA1GRE01", lv:"A1", topic:"greetings", es:"Hola, buenos días.", en:"Hello, good morning."},
  {id:"dA1GRE02", lv:"A1", topic:"greetings", es:"¿Cómo estás?", en:"How are you?"},
  {id:"dA1GRE03", lv:"A1", topic:"greetings", es:"Muy bien, gracias.", en:"Very well, thank you."},
  {id:"dA1GRE04", lv:"A1", topic:"greetings", es:"Me llamo Sonja.", en:"My name is Sonja."},
  {id:"dA1GRE05", lv:"A1", topic:"greetings", es:"¿Cómo te llamas?", en:"What's your name?"},
  {id:"dA1GRE06", lv:"A1", topic:"greetings", es:"Encantada de conocerte.", en:"Nice to meet you."},
  {id:"dA1GRE07", lv:"A1", topic:"greetings", es:"¿De dónde eres?", en:"Where are you from?"},
  {id:"dA1GRE08", lv:"A1", topic:"greetings", es:"Soy de Holanda.", en:"I'm from Holland."},
  {id:"dA1GRE09", lv:"A1", topic:"greetings", es:"Adiós, hasta luego.", en:"Goodbye, see you later."},
  {id:"dA1GRE10", lv:"A1", topic:"greetings", es:"Buenas noches.", en:"Good night."},
  // family
  {id:"dA1FAM01", lv:"A1", topic:"family", es:"Esta es mi familia.", en:"This is my family."},
  {id:"dA1FAM02", lv:"A1", topic:"family", es:"Tengo dos hermanos.", en:"I have two brothers."},
  {id:"dA1FAM03", lv:"A1", topic:"family", es:"Mi madre se llama Ana.", en:"My mother's name is Ana."},
  {id:"dA1FAM04", lv:"A1", topic:"family", es:"Mi padre trabaja mucho.", en:"My father works a lot."},
  {id:"dA1FAM05", lv:"A1", topic:"family", es:"Tengo un hijo.", en:"I have one son."},
  {id:"dA1FAM06", lv:"A1", topic:"family", es:"Mi hermana es simpática.", en:"My sister is nice."},
  {id:"dA1FAM07", lv:"A1", topic:"family", es:"¿Tienes hijos?", en:"Do you have children?"},
  {id:"dA1FAM08", lv:"A1", topic:"family", es:"Vivo con mi familia.", en:"I live with my family."},
  {id:"dA1FAM09", lv:"A1", topic:"family", es:"Mi abuela es mayor.", en:"My grandmother is old."},
  {id:"dA1FAM10", lv:"A1", topic:"family", es:"Quiero mucho a mi familia.", en:"I love my family a lot."},
  // food
  {id:"dA1FOO01", lv:"A1", topic:"food", es:"Tengo hambre.", en:"I'm hungry."},
  {id:"dA1FOO02", lv:"A1", topic:"food", es:"Quiero un café, por favor.", en:"I want a coffee, please."},
  {id:"dA1FOO03", lv:"A1", topic:"food", es:"La cuenta, por favor.", en:"The bill, please."},
  {id:"dA1FOO04", lv:"A1", topic:"food", es:"Está muy rico.", en:"It's very tasty."},
  {id:"dA1FOO05", lv:"A1", topic:"food", es:"¿Qué quieres comer?", en:"What do you want to eat?"},
  {id:"dA1FOO06", lv:"A1", topic:"food", es:"Me gusta el pan.", en:"I like bread."},
  {id:"dA1FOO07", lv:"A1", topic:"food", es:"No como carne.", en:"I don't eat meat."},
  {id:"dA1FOO08", lv:"A1", topic:"food", es:"Un vaso de agua, por favor.", en:"A glass of water, please."},
  {id:"dA1FOO09", lv:"A1", topic:"food", es:"¿Tienes sed?", en:"Are you thirsty?"},
  {id:"dA1FOO10", lv:"A1", topic:"food", es:"El desayuno es a las ocho.", en:"Breakfast is at eight."},
  // shopping
  {id:"dA1SHO01", lv:"A1", topic:"shopping", es:"¿Cuánto cuesta?", en:"How much does it cost?"},
  {id:"dA1SHO02", lv:"A1", topic:"shopping", es:"Es muy caro.", en:"It's very expensive."},
  {id:"dA1SHO03", lv:"A1", topic:"shopping", es:"Quiero comprar esto.", en:"I want to buy this."},
  {id:"dA1SHO04", lv:"A1", topic:"shopping", es:"¿Puedo pagar con tarjeta?", en:"Can I pay by card?"},
  {id:"dA1SHO05", lv:"A1", topic:"shopping", es:"No tengo dinero.", en:"I don't have money."},
  {id:"dA1SHO06", lv:"A1", topic:"shopping", es:"Busco una tienda.", en:"I'm looking for a shop."},
  {id:"dA1SHO07", lv:"A1", topic:"shopping", es:"Solo estoy mirando.", en:"I'm just looking."},
  {id:"dA1SHO08", lv:"A1", topic:"shopping", es:"Aquí tiene.", en:"Here you go."},
  {id:"dA1SHO09", lv:"A1", topic:"shopping", es:"¿A qué hora cierra?", en:"What time does it close?"},
  {id:"dA1SHO10", lv:"A1", topic:"shopping", es:"Es barato.", en:"It's cheap."},
  // travel
  {id:"dA1TRA01", lv:"A1", topic:"travel", es:"¿Dónde está el baño?", en:"Where is the bathroom?"},
  {id:"dA1TRA02", lv:"A1", topic:"travel", es:"Quiero un billete.", en:"I want a ticket."},
  {id:"dA1TRA03", lv:"A1", topic:"travel", es:"¿Está lejos?", en:"Is it far?"},
  {id:"dA1TRA04", lv:"A1", topic:"travel", es:"Gire a la derecha.", en:"Turn right."},
  {id:"dA1TRA05", lv:"A1", topic:"travel", es:"Gire a la izquierda.", en:"Turn left."},
  {id:"dA1TRA06", lv:"A1", topic:"travel", es:"Todo recto.", en:"Straight ahead."},
  {id:"dA1TRA07", lv:"A1", topic:"travel", es:"¿Dónde está la estación?", en:"Where is the station?"},
  {id:"dA1TRA08", lv:"A1", topic:"travel", es:"Estoy perdida.", en:"I'm lost."},
  {id:"dA1TRA09", lv:"A1", topic:"travel", es:"Voy a la playa.", en:"I'm going to the beach."},
  {id:"dA1TRA10", lv:"A1", topic:"travel", es:"El tren sale ahora.", en:"The train leaves now."},
  // routine
  {id:"dA1ROU01", lv:"A1", topic:"routine", es:"Me levanto a las siete.", en:"I get up at seven."},
  {id:"dA1ROU02", lv:"A1", topic:"routine", es:"¿Qué hora es?", en:"What time is it?"},
  {id:"dA1ROU03", lv:"A1", topic:"routine", es:"Son las tres.", en:"It's three o'clock."},
  {id:"dA1ROU04", lv:"A1", topic:"routine", es:"Hoy es lunes.", en:"Today is Monday."},
  {id:"dA1ROU05", lv:"A1", topic:"routine", es:"Trabajo por la mañana.", en:"I work in the morning."},
  {id:"dA1ROU06", lv:"A1", topic:"routine", es:"Duermo ocho horas.", en:"I sleep eight hours."},
  {id:"dA1ROU07", lv:"A1", topic:"routine", es:"Como a la una.", en:"I eat at one."},
  {id:"dA1ROU08", lv:"A1", topic:"routine", es:"Voy a casa.", en:"I'm going home."},
  {id:"dA1ROU09", lv:"A1", topic:"routine", es:"Estoy cansada.", en:"I'm tired."},
  {id:"dA1ROU10", lv:"A1", topic:"routine", es:"Mañana es sábado.", en:"Tomorrow is Saturday."},
  // health
  {id:"dA1HEA01", lv:"A1", topic:"health", es:"Me duele la cabeza.", en:"My head hurts."},
  {id:"dA1HEA02", lv:"A1", topic:"health", es:"Estoy enferma.", en:"I'm sick."},
  {id:"dA1HEA03", lv:"A1", topic:"health", es:"Necesito un médico.", en:"I need a doctor."},
  {id:"dA1HEA04", lv:"A1", topic:"health", es:"No me siento bien.", en:"I don't feel well."},
  {id:"dA1HEA05", lv:"A1", topic:"health", es:"Me duele el estómago.", en:"My stomach hurts."},
  {id:"dA1HEA06", lv:"A1", topic:"health", es:"Estoy mejor hoy.", en:"I'm better today."},
  {id:"dA1HEA07", lv:"A1", topic:"health", es:"Necesito descansar.", en:"I need to rest."},
  {id:"dA1HEA08", lv:"A1", topic:"health", es:"¿Dónde hay una farmacia?", en:"Where is there a pharmacy?"},
  {id:"dA1HEA09", lv:"A1", topic:"health", es:"Tengo frío.", en:"I'm cold."},
  {id:"dA1HEA10", lv:"A1", topic:"health", es:"Tengo calor.", en:"I'm hot."},
  // work
  {id:"dA1WOR01", lv:"A1", topic:"work", es:"Soy profesora.", en:"I'm a teacher."},
  {id:"dA1WOR02", lv:"A1", topic:"work", es:"¿En qué trabajas?", en:"What do you do for work?"},
  {id:"dA1WOR03", lv:"A1", topic:"work", es:"Trabajo en una oficina.", en:"I work in an office."},
  {id:"dA1WOR04", lv:"A1", topic:"work", es:"Estudio español.", en:"I study Spanish."},
  {id:"dA1WOR05", lv:"A1", topic:"work", es:"Me gusta mi trabajo.", en:"I like my job."},
  {id:"dA1WOR06", lv:"A1", topic:"work", es:"Tengo una reunión.", en:"I have a meeting."},
  {id:"dA1WOR07", lv:"A1", topic:"work", es:"Empiezo a las nueve.", en:"I start at nine."},
  {id:"dA1WOR08", lv:"A1", topic:"work", es:"Hoy no trabajo.", en:"I'm not working today."},
  {id:"dA1WOR09", lv:"A1", topic:"work", es:"Aprendo mucho.", en:"I learn a lot."},
  {id:"dA1WOR10", lv:"A1", topic:"work", es:"¿Dónde trabajas?", en:"Where do you work?"},
  // weather
  {id:"dA1WEA01", lv:"A1", topic:"weather", es:"Hace sol.", en:"It's sunny."},
  {id:"dA1WEA02", lv:"A1", topic:"weather", es:"Hace frío.", en:"It's cold."},
  {id:"dA1WEA03", lv:"A1", topic:"weather", es:"Está lloviendo.", en:"It's raining."},
  {id:"dA1WEA04", lv:"A1", topic:"weather", es:"Hace calor hoy.", en:"It's hot today."},
  {id:"dA1WEA05", lv:"A1", topic:"weather", es:"El cielo está azul.", en:"The sky is blue."},
  {id:"dA1WEA06", lv:"A1", topic:"weather", es:"Hace viento.", en:"It's windy."},
  {id:"dA1WEA07", lv:"A1", topic:"weather", es:"Me gusta el verano.", en:"I like summer."},
  {id:"dA1WEA08", lv:"A1", topic:"weather", es:"En invierno nieva.", en:"In winter it snows."},
  {id:"dA1WEA09", lv:"A1", topic:"weather", es:"¿Qué tiempo hace?", en:"What's the weather like?"},
  {id:"dA1WEA10", lv:"A1", topic:"weather", es:"Hoy hace buen tiempo.", en:"Today the weather is nice."},
  // social
  {id:"dA1SOC01", lv:"A1", topic:"social", es:"Estoy muy contenta.", en:"I'm very happy."},
  {id:"dA1SOC02", lv:"A1", topic:"social", es:"¿Quieres un café?", en:"Do you want a coffee?"},
  {id:"dA1SOC03", lv:"A1", topic:"social", es:"¡Qué bien!", en:"How nice!"},
  {id:"dA1SOC04", lv:"A1", topic:"social", es:"Estoy triste.", en:"I'm sad."},
  {id:"dA1SOC05", lv:"A1", topic:"social", es:"¿Vamos al parque?", en:"Shall we go to the park?"},
  {id:"dA1SOC06", lv:"A1", topic:"social", es:"Me gusta mucho.", en:"I like it a lot."},
  {id:"dA1SOC07", lv:"A1", topic:"social", es:"¡Feliz cumpleaños!", en:"Happy birthday!"},
  {id:"dA1SOC08", lv:"A1", topic:"social", es:"¿Nos vemos mañana?", en:"See you tomorrow?"},
  {id:"dA1SOC09", lv:"A1", topic:"social", es:"Lo siento.", en:"I'm sorry."},
  {id:"dA1SOC10", lv:"A1", topic:"social", es:"No pasa nada.", en:"It's no problem."},

  /* ===================== A2 ===================== */
  // greetings
  {id:"dA2GRE01", lv:"A2", topic:"greetings", es:"¿Cuánto tiempo llevas aquí?", en:"How long have you been here?"},
  {id:"dA2GRE02", lv:"A2", topic:"greetings", es:"¿Puedo presentarte a mi amiga?", en:"Can I introduce you to my friend?"},
  {id:"dA2GRE03", lv:"A2", topic:"greetings", es:"Ha pasado mucho tiempo.", en:"It's been a long time."},
  {id:"dA2GRE04", lv:"A2", topic:"greetings", es:"¿Qué tal el fin de semana?", en:"How was the weekend?"},
  {id:"dA2GRE05", lv:"A2", topic:"greetings", es:"Me alegro de verte.", en:"I'm glad to see you."},
  {id:"dA2GRE06", lv:"A2", topic:"greetings", es:"¿A qué te dedicas?", en:"What do you do?"},
  {id:"dA2GRE07", lv:"A2", topic:"greetings", es:"Un placer conocerte.", en:"A pleasure to meet you."},
  {id:"dA2GRE08", lv:"A2", topic:"greetings", es:"Saludos a tu familia.", en:"Regards to your family."},
  {id:"dA2GRE09", lv:"A2", topic:"greetings", es:"Que tengas un buen día.", en:"Have a good day."},
  {id:"dA2GRE10", lv:"A2", topic:"greetings", es:"Nos vemos pronto.", en:"See you soon."},
  // family
  {id:"dA2FAM01", lv:"A2", topic:"family", es:"Mi hermano se casó el año pasado.", en:"My brother got married last year."},
  {id:"dA2FAM02", lv:"A2", topic:"family", es:"Mis padres están jubilados.", en:"My parents are retired."},
  {id:"dA2FAM03", lv:"A2", topic:"family", es:"Me llevo bien con mi hermana.", en:"I get along well with my sister."},
  {id:"dA2FAM04", lv:"A2", topic:"family", es:"Mi hijo estudia en la universidad.", en:"My son studies at university."},
  {id:"dA2FAM05", lv:"A2", topic:"family", es:"Tenemos un perro y un gato.", en:"We have a dog and a cat."},
  {id:"dA2FAM06", lv:"A2", topic:"family", es:"Mi familia es muy unida.", en:"My family is very close."},
  {id:"dA2FAM07", lv:"A2", topic:"family", es:"Visito a mis padres los domingos.", en:"I visit my parents on Sundays."},
  {id:"dA2FAM08", lv:"A2", topic:"family", es:"Mi abuelo tiene ochenta años.", en:"My grandfather is eighty."},
  {id:"dA2FAM09", lv:"A2", topic:"family", es:"Nos parecemos mucho.", en:"We look a lot alike."},
  {id:"dA2FAM10", lv:"A2", topic:"family", es:"Vivimos juntos desde hace tres años.", en:"We've lived together for three years."},
  // food
  {id:"dA2FOO01", lv:"A2", topic:"food", es:"¿Me trae la carta, por favor?", en:"Could you bring the menu, please?"},
  {id:"dA2FOO02", lv:"A2", topic:"food", es:"¿Qué me recomienda?", en:"What do you recommend?"},
  {id:"dA2FOO03", lv:"A2", topic:"food", es:"Soy alérgica a los frutos secos.", en:"I'm allergic to nuts."},
  {id:"dA2FOO04", lv:"A2", topic:"food", es:"Para mí, la sopa.", en:"For me, the soup."},
  {id:"dA2FOO05", lv:"A2", topic:"food", es:"La comida estaba deliciosa.", en:"The food was delicious."},
  {id:"dA2FOO06", lv:"A2", topic:"food", es:"¿Nos trae la cuenta?", en:"Can you bring us the bill?"},
  {id:"dA2FOO07", lv:"A2", topic:"food", es:"Prefiero algo ligero.", en:"I prefer something light."},
  {id:"dA2FOO08", lv:"A2", topic:"food", es:"¿Tienen opciones vegetarianas?", en:"Do you have vegetarian options?"},
  {id:"dA2FOO09", lv:"A2", topic:"food", es:"¿Está incluido el pan?", en:"Is bread included?"},
  {id:"dA2FOO10", lv:"A2", topic:"food", es:"Estaba todo buenísimo.", en:"It was all delicious."},
  // shopping
  {id:"dA2SHO01", lv:"A2", topic:"shopping", es:"¿Puedo probármelo?", en:"Can I try it on?"},
  {id:"dA2SHO02", lv:"A2", topic:"shopping", es:"Es demasiado grande.", en:"It's too big."},
  {id:"dA2SHO03", lv:"A2", topic:"shopping", es:"¿Tiene una talla más pequeña?", en:"Do you have a smaller size?"},
  {id:"dA2SHO04", lv:"A2", topic:"shopping", es:"¿Hay descuento?", en:"Is there a discount?"},
  {id:"dA2SHO05", lv:"A2", topic:"shopping", es:"Me lo llevo.", en:"I'll take it."},
  {id:"dA2SHO06", lv:"A2", topic:"shopping", es:"¿Dónde están los probadores?", en:"Where are the fitting rooms?"},
  {id:"dA2SHO07", lv:"A2", topic:"shopping", es:"Quisiera devolver esto.", en:"I'd like to return this."},
  {id:"dA2SHO08", lv:"A2", topic:"shopping", es:"¿Tienen algo más barato?", en:"Do you have anything cheaper?"},
  {id:"dA2SHO09", lv:"A2", topic:"shopping", es:"¿Me da una bolsa, por favor?", en:"Can I have a bag, please?"},
  {id:"dA2SHO10", lv:"A2", topic:"shopping", es:"¿Aceptan tarjeta?", en:"Do you accept card?"},
  // travel
  {id:"dA2TRA01", lv:"A2", topic:"travel", es:"¿Cómo llego al centro?", en:"How do I get to the center?"},
  {id:"dA2TRA02", lv:"A2", topic:"travel", es:"¿Cuánto tarda en tren?", en:"How long does it take by train?"},
  {id:"dA2TRA03", lv:"A2", topic:"travel", es:"Quisiera reservar una habitación.", en:"I'd like to book a room."},
  {id:"dA2TRA04", lv:"A2", topic:"travel", es:"Perdí mi maleta.", en:"I lost my suitcase."},
  {id:"dA2TRA05", lv:"A2", topic:"travel", es:"¿Puede llamar a un taxi?", en:"Can you call a taxi?"},
  {id:"dA2TRA06", lv:"A2", topic:"travel", es:"¿Hay wifi en el hotel?", en:"Is there wifi in the hotel?"},
  {id:"dA2TRA07", lv:"A2", topic:"travel", es:"¿Está cerca de la playa?", en:"Is it near the beach?"},
  {id:"dA2TRA08", lv:"A2", topic:"travel", es:"¿Me puede indicar en el mapa?", en:"Can you show me on the map?"},
  {id:"dA2TRA09", lv:"A2", topic:"travel", es:"El vuelo se retrasó.", en:"The flight was delayed."},
  {id:"dA2TRA10", lv:"A2", topic:"travel", es:"¿A qué hora es el check-in?", en:"What time is check-in?"},
  // routine
  {id:"dA2ROU01", lv:"A2", topic:"routine", es:"Normalmente me acuesto tarde.", en:"I usually go to bed late."},
  {id:"dA2ROU02", lv:"A2", topic:"routine", es:"Los fines de semana descanso.", en:"On weekends I rest."},
  {id:"dA2ROU03", lv:"A2", topic:"routine", es:"Antes de trabajar, tomo café.", en:"Before working, I have coffee."},
  {id:"dA2ROU04", lv:"A2", topic:"routine", es:"Ayer me levanté temprano.", en:"Yesterday I got up early."},
  {id:"dA2ROU05", lv:"A2", topic:"routine", es:"Suelo ir al gimnasio.", en:"I usually go to the gym."},
  {id:"dA2ROU06", lv:"A2", topic:"routine", es:"Después de comer, doy un paseo.", en:"After eating, I take a walk."},
  {id:"dA2ROU07", lv:"A2", topic:"routine", es:"Esta semana estoy muy ocupada.", en:"This week I'm very busy."},
  {id:"dA2ROU08", lv:"A2", topic:"routine", es:"Voy al trabajo en bici.", en:"I go to work by bike."},
  {id:"dA2ROU09", lv:"A2", topic:"routine", es:"Por la noche veo la tele.", en:"At night I watch TV."},
  {id:"dA2ROU10", lv:"A2", topic:"routine", es:"Hoy tengo el día libre.", en:"Today I have the day off."},
  // health
  {id:"dA2HEA01", lv:"A2", topic:"health", es:"Me encuentro un poco mal.", en:"I feel a bit unwell."},
  {id:"dA2HEA02", lv:"A2", topic:"health", es:"Creo que tengo fiebre.", en:"I think I have a fever."},
  {id:"dA2HEA03", lv:"A2", topic:"health", es:"Necesito una cita con el médico.", en:"I need an appointment with the doctor."},
  {id:"dA2HEA04", lv:"A2", topic:"health", es:"¿Tiene algo para la tos?", en:"Do you have something for a cough?"},
  {id:"dA2HEA05", lv:"A2", topic:"health", es:"Estoy resfriada.", en:"I have a cold."},
  {id:"dA2HEA06", lv:"A2", topic:"health", es:"Me tomo una pastilla al día.", en:"I take one pill a day."},
  {id:"dA2HEA07", lv:"A2", topic:"health", es:"Debería ir al dentista.", en:"I should go to the dentist."},
  {id:"dA2HEA08", lv:"A2", topic:"health", es:"Estoy agotada.", en:"I'm exhausted."},
  {id:"dA2HEA09", lv:"A2", topic:"health", es:"Espero recuperarme pronto.", en:"I hope to recover soon."},
  {id:"dA2HEA10", lv:"A2", topic:"health", es:"Me duele la espalda.", en:"My back hurts."},
  // work
  {id:"dA2WOR01", lv:"A2", topic:"work", es:"Trabajo desde casa.", en:"I work from home."},
  {id:"dA2WOR02", lv:"A2", topic:"work", es:"Tengo mucho que hacer hoy.", en:"I have a lot to do today."},
  {id:"dA2WOR03", lv:"A2", topic:"work", es:"Tenemos una reunión a las diez.", en:"We have a meeting at ten."},
  {id:"dA2WOR04", lv:"A2", topic:"work", es:"Estoy buscando trabajo.", en:"I'm looking for a job."},
  {id:"dA2WOR05", lv:"A2", topic:"work", es:"Me gusta trabajar en equipo.", en:"I like working in a team."},
  {id:"dA2WOR06", lv:"A2", topic:"work", es:"El proyecto va bien.", en:"The project is going well."},
  {id:"dA2WOR07", lv:"A2", topic:"work", es:"Terminé el informe.", en:"I finished the report."},
  {id:"dA2WOR08", lv:"A2", topic:"work", es:"¿Puedes ayudarme con esto?", en:"Can you help me with this?"},
  {id:"dA2WOR09", lv:"A2", topic:"work", es:"Estoy aprendiendo cosas nuevas.", en:"I'm learning new things."},
  {id:"dA2WOR10", lv:"A2", topic:"work", es:"Mi jefe es muy amable.", en:"My boss is very kind."},
  // weather
  {id:"dA2WEA01", lv:"A2", topic:"weather", es:"Parece que va a llover.", en:"It looks like it's going to rain."},
  {id:"dA2WEA02", lv:"A2", topic:"weather", es:"Hace mucho calor esta semana.", en:"It's very hot this week."},
  {id:"dA2WEA03", lv:"A2", topic:"weather", es:"En primavera hace buen tiempo.", en:"In spring the weather is nice."},
  {id:"dA2WEA04", lv:"A2", topic:"weather", es:"Ayer hubo tormenta.", en:"Yesterday there was a storm."},
  {id:"dA2WEA05", lv:"A2", topic:"weather", es:"No olvides el paraguas.", en:"Don't forget the umbrella."},
  {id:"dA2WEA06", lv:"A2", topic:"weather", es:"Hace demasiado frío para salir.", en:"It's too cold to go out."},
  {id:"dA2WEA07", lv:"A2", topic:"weather", es:"Mañana estará nublado.", en:"Tomorrow it will be cloudy."},
  {id:"dA2WEA08", lv:"A2", topic:"weather", es:"Me encanta cuando hace sol.", en:"I love it when it's sunny."},
  {id:"dA2WEA09", lv:"A2", topic:"weather", es:"El invierno es muy largo.", en:"Winter is very long."},
  {id:"dA2WEA10", lv:"A2", topic:"weather", es:"El clima aquí es agradable.", en:"The climate here is pleasant."},
  // social
  {id:"dA2SOC01", lv:"A2", topic:"social", es:"¿Te apetece salir esta noche?", en:"Do you feel like going out tonight?"},
  {id:"dA2SOC02", lv:"A2", topic:"social", es:"Quedamos a las ocho, ¿vale?", en:"Let's meet at eight, okay?"},
  {id:"dA2SOC03", lv:"A2", topic:"social", es:"Lo pasé muy bien ayer.", en:"I had a great time yesterday."},
  {id:"dA2SOC04", lv:"A2", topic:"social", es:"Estoy un poco nerviosa.", en:"I'm a bit nervous."},
  {id:"dA2SOC05", lv:"A2", topic:"social", es:"Me encantaría ir.", en:"I'd love to go."},
  {id:"dA2SOC06", lv:"A2", topic:"social", es:"No estoy de humor hoy.", en:"I'm not in the mood today."},
  {id:"dA2SOC07", lv:"A2", topic:"social", es:"Gracias por invitarme.", en:"Thanks for inviting me."},
  {id:"dA2SOC08", lv:"A2", topic:"social", es:"¿Puedo llevar a un amigo?", en:"Can I bring a friend?"},
  {id:"dA2SOC09", lv:"A2", topic:"social", es:"Nos vemos el viernes.", en:"See you Friday."},
  {id:"dA2SOC10", lv:"A2", topic:"social", es:"¿Qué te parece la idea?", en:"What do you think of the idea?"},

  /* ===================== B1 ===================== */
  // greetings
  {id:"dB1GRE01", lv:"B1", topic:"greetings", es:"Hace siglos que no nos vemos.", en:"We haven't seen each other in ages."},
  {id:"dB1GRE02", lv:"B1", topic:"greetings", es:"Me han hablado mucho de ti.", en:"I've heard a lot about you."},
  {id:"dB1GRE03", lv:"B1", topic:"greetings", es:"Justo estaba pensando en ti.", en:"I was just thinking about you."},
  {id:"dB1GRE04", lv:"B1", topic:"greetings", es:"¿Cómo te va la vida?", en:"How's life going?"},
  {id:"dB1GRE05", lv:"B1", topic:"greetings", es:"Deberíamos quedar más a menudo.", en:"We should meet up more often."},
  {id:"dB1GRE06", lv:"B1", topic:"greetings", es:"Perdona que llegue tarde.", en:"Sorry I'm late."},
  {id:"dB1GRE07", lv:"B1", topic:"greetings", es:"Me suena tu cara.", en:"Your face looks familiar."},
  {id:"dB1GRE08", lv:"B1", topic:"greetings", es:"Encantado de volver a verte.", en:"Nice to see you again."},
  {id:"dB1GRE09", lv:"B1", topic:"greetings", es:"Dale recuerdos de mi parte.", en:"Give him my regards."},
  {id:"dB1GRE10", lv:"B1", topic:"greetings", es:"¿Te importa si te tuteo?", en:"Do you mind if I use 'tú' with you?"},
  // family
  {id:"dB1FAM01", lv:"B1", topic:"family", es:"Aunque discutimos, nos queremos mucho.", en:"Although we argue, we love each other a lot."},
  {id:"dB1FAM02", lv:"B1", topic:"family", es:"Mis padres siempre me han apoyado.", en:"My parents have always supported me."},
  {id:"dB1FAM03", lv:"B1", topic:"family", es:"Desde que nació el bebé, estamos cansados.", en:"Since the baby was born, we're tired."},
  {id:"dB1FAM04", lv:"B1", topic:"family", es:"Me gustaría tener una familia grande.", en:"I'd like to have a big family."},
  {id:"dB1FAM05", lv:"B1", topic:"family", es:"Cuando era pequeña, vivíamos en el campo.", en:"When I was little, we lived in the countryside."},
  {id:"dB1FAM06", lv:"B1", topic:"family", es:"Es difícil verlos tan a menudo.", en:"It's hard to see them so often."},
  {id:"dB1FAM07", lv:"B1", topic:"family", es:"Mi hija se ha independizado.", en:"My daughter has moved out on her own."},
  {id:"dB1FAM08", lv:"B1", topic:"family", es:"Siempre nos reunimos en Navidad.", en:"We always get together at Christmas."},
  {id:"dB1FAM09", lv:"B1", topic:"family", es:"Ojalá viviéramos más cerca.", en:"I wish we lived closer."},
  {id:"dB1FAM10", lv:"B1", topic:"family", es:"Nos parecemos en el carácter.", en:"We're alike in character."},
  // food
  {id:"dB1FOO01", lv:"B1", topic:"food", es:"Este restaurante tiene muy buena fama.", en:"This restaurant has a very good reputation."},
  {id:"dB1FOO02", lv:"B1", topic:"food", es:"Me han dicho que la paella es excelente.", en:"I've been told the paella is excellent."},
  {id:"dB1FOO03", lv:"B1", topic:"food", es:"Prefiero cocinar en casa que salir.", en:"I prefer cooking at home to eating out."},
  {id:"dB1FOO04", lv:"B1", topic:"food", es:"¿Te importaría si compartimos el postre?", en:"Would you mind if we share the dessert?"},
  {id:"dB1FOO05", lv:"B1", topic:"food", es:"La comida estaba buena, pero un poco cara.", en:"The food was good, but a bit expensive."},
  {id:"dB1FOO06", lv:"B1", topic:"food", es:"Nunca había probado esto antes.", en:"I'd never tried this before."},
  {id:"dB1FOO07", lv:"B1", topic:"food", es:"Si tuviera tiempo, cocinaría más.", en:"If I had time, I'd cook more."},
  {id:"dB1FOO08", lv:"B1", topic:"food", es:"Me gustaría aprender a hacer tortilla.", en:"I'd like to learn to make tortilla."},
  {id:"dB1FOO09", lv:"B1", topic:"food", es:"No creo que quede sitio para el postre.", en:"I don't think there's room for dessert."},
  {id:"dB1FOO10", lv:"B1", topic:"food", es:"Aunque no tengo hambre, comeré algo.", en:"Although I'm not hungry, I'll eat something."},
  // shopping
  {id:"dB1SHO01", lv:"B1", topic:"shopping", es:"Estaba buscando algo parecido a esto.", en:"I was looking for something like this."},
  {id:"dB1SHO02", lv:"B1", topic:"shopping", es:"¿Podría cambiarlo por otra talla?", en:"Could I exchange it for another size?"},
  {id:"dB1SHO03", lv:"B1", topic:"shopping", es:"Me lo pensaré y luego vuelvo.", en:"I'll think about it and come back."},
  {id:"dB1SHO04", lv:"B1", topic:"shopping", es:"Salió más caro de lo que esperaba.", en:"It came out more expensive than I expected."},
  {id:"dB1SHO05", lv:"B1", topic:"shopping", es:"Compré esto en las rebajas.", en:"I bought this in the sales."},
  {id:"dB1SHO06", lv:"B1", topic:"shopping", es:"Si no me queda bien, lo devuelvo.", en:"If it doesn't fit, I'll return it."},
  {id:"dB1SHO07", lv:"B1", topic:"shopping", es:"Me he gastado demasiado este mes.", en:"I've spent too much this month."},
  {id:"dB1SHO08", lv:"B1", topic:"shopping", es:"Merece la pena por la calidad.", en:"It's worth it for the quality."},
  {id:"dB1SHO09", lv:"B1", topic:"shopping", es:"No sabía cuál elegir.", en:"I didn't know which one to choose."},
  {id:"dB1SHO10", lv:"B1", topic:"shopping", es:"¿Tienen el recibo, por si acaso?", en:"Do you have the receipt, just in case?"},
  // travel
  {id:"dB1TRA01", lv:"B1", topic:"travel", es:"Si hace buen tiempo, iremos a la montaña.", en:"If the weather is good, we'll go to the mountains."},
  {id:"dB1TRA02", lv:"B1", topic:"travel", es:"Nunca he estado en el sur de España.", en:"I've never been to the south of Spain."},
  {id:"dB1TRA03", lv:"B1", topic:"travel", es:"Me gustaría quedarme unos días más.", en:"I'd like to stay a few more days."},
  {id:"dB1TRA04", lv:"B1", topic:"travel", es:"El hotel no era como en las fotos.", en:"The hotel wasn't like in the photos."},
  {id:"dB1TRA05", lv:"B1", topic:"travel", es:"¿Sabes si hay un autobús directo?", en:"Do you know if there's a direct bus?"},
  {id:"dB1TRA06", lv:"B1", topic:"travel", es:"Perdimos el tren por cinco minutos.", en:"We missed the train by five minutes."},
  {id:"dB1TRA07", lv:"B1", topic:"travel", es:"Espero que el vuelo no se retrase.", en:"I hope the flight isn't delayed."},
  {id:"dB1TRA08", lv:"B1", topic:"travel", es:"Viajar sola me da un poco de miedo.", en:"Traveling alone scares me a little."},
  {id:"dB1TRA09", lv:"B1", topic:"travel", es:"En cuanto lleguemos, te aviso.", en:"As soon as we arrive, I'll let you know."},
  {id:"dB1TRA10", lv:"B1", topic:"travel", es:"Aunque estaba cansada, seguí caminando.", en:"Although I was tired, I kept walking."},
  // routine
  {id:"dB1ROU01", lv:"B1", topic:"routine", es:"Últimamente no tengo tiempo para nada.", en:"Lately I don't have time for anything."},
  {id:"dB1ROU02", lv:"B1", topic:"routine", es:"Solía levantarme más temprano.", en:"I used to get up earlier."},
  {id:"dB1ROU03", lv:"B1", topic:"routine", es:"Cuando termine el trabajo, descansaré.", en:"When I finish work, I'll rest."},
  {id:"dB1ROU04", lv:"B1", topic:"routine", es:"Me cuesta madrugar en invierno.", en:"I find it hard to get up early in winter."},
  {id:"dB1ROU05", lv:"B1", topic:"routine", es:"Intento hacer ejercicio cada día.", en:"I try to exercise every day."},
  {id:"dB1ROU06", lv:"B1", topic:"routine", es:"Antes veía más la tele que ahora.", en:"I used to watch more TV than now."},
  {id:"dB1ROU07", lv:"B1", topic:"routine", es:"Si pudiera, dormiría toda la mañana.", en:"If I could, I'd sleep all morning."},
  {id:"dB1ROU08", lv:"B1", topic:"routine", es:"Tengo la agenda llena esta semana.", en:"My schedule is full this week."},
  {id:"dB1ROU09", lv:"B1", topic:"routine", es:"Suelo desconectar los fines de semana.", en:"I usually switch off on weekends."},
  {id:"dB1ROU10", lv:"B1", topic:"routine", es:"Ojalá tuviera más tiempo libre.", en:"I wish I had more free time."},
  // health
  {id:"dB1HEA01", lv:"B1", topic:"health", es:"Llevo varios días sin dormir bien.", en:"I've spent several days not sleeping well."},
  {id:"dB1HEA02", lv:"B1", topic:"health", es:"El médico me dijo que descansara.", en:"The doctor told me to rest."},
  {id:"dB1HEA03", lv:"B1", topic:"health", es:"Si sigo así, me pondré enferma.", en:"If I keep going like this, I'll get sick."},
  {id:"dB1HEA04", lv:"B1", topic:"health", es:"Me han recetado unos antibióticos.", en:"I've been prescribed some antibiotics."},
  {id:"dB1HEA05", lv:"B1", topic:"health", es:"Debería cuidarme más.", en:"I should take better care of myself."},
  {id:"dB1HEA06", lv:"B1", topic:"health", es:"Desde que hago deporte, me siento mejor.", en:"Since I started exercising, I feel better."},
  {id:"dB1HEA07", lv:"B1", topic:"health", es:"Espero que no sea nada grave.", en:"I hope it's nothing serious."},
  {id:"dB1HEA08", lv:"B1", topic:"health", es:"Tengo que pedir cita con el especialista.", en:"I have to make an appointment with the specialist."},
  {id:"dB1HEA09", lv:"B1", topic:"health", es:"Me conviene comer más sano.", en:"It would be good for me to eat healthier."},
  {id:"dB1HEA10", lv:"B1", topic:"health", es:"Aunque me duele, puedo caminar.", en:"Although it hurts, I can walk."},
  // work
  {id:"dB1WOR01", lv:"B1", topic:"work", es:"Llevo cinco años en esta empresa.", en:"I've been at this company for five years."},
  {id:"dB1WOR02", lv:"B1", topic:"work", es:"Me gustaría cambiar de trabajo.", en:"I'd like to change jobs."},
  {id:"dB1WOR03", lv:"B1", topic:"work", es:"Aunque es estresante, me gusta lo que hago.", en:"Although it's stressful, I like what I do."},
  {id:"dB1WOR04", lv:"B1", topic:"work", es:"Tengo que entregar el informe mañana.", en:"I have to hand in the report tomorrow."},
  {id:"dB1WOR05", lv:"B1", topic:"work", es:"Si me ascienden, ganaré más.", en:"If I get promoted, I'll earn more."},
  {id:"dB1WOR06", lv:"B1", topic:"work", es:"Estoy aprendiendo a gestionar mi tiempo.", en:"I'm learning to manage my time."},
  {id:"dB1WOR07", lv:"B1", topic:"work", es:"Mi jefe valora el esfuerzo.", en:"My boss values effort."},
  {id:"dB1WOR08", lv:"B1", topic:"work", es:"Me llevo bien con mis compañeros.", en:"I get along well with my colleagues."},
  {id:"dB1WOR09", lv:"B1", topic:"work", es:"Ojalá pudiera trabajar menos horas.", en:"I wish I could work fewer hours."},
  {id:"dB1WOR10", lv:"B1", topic:"work", es:"Últimamente hay mucho que hacer.", en:"Lately there's a lot to do."},
  // weather
  {id:"dB1WEA01", lv:"B1", topic:"weather", es:"Parece que el tiempo va a cambiar.", en:"It looks like the weather is going to change."},
  {id:"dB1WEA02", lv:"B1", topic:"weather", es:"Aunque llueva, saldremos igual.", en:"Even if it rains, we'll go out anyway."},
  {id:"dB1WEA03", lv:"B1", topic:"weather", es:"El verano pasado hizo un calor horrible.", en:"Last summer it was terribly hot."},
  {id:"dB1WEA04", lv:"B1", topic:"weather", es:"Dicen que mañana bajará la temperatura.", en:"They say the temperature will drop tomorrow."},
  {id:"dB1WEA05", lv:"B1", topic:"weather", es:"No soporto el frío del invierno.", en:"I can't stand the winter cold."},
  {id:"dB1WEA06", lv:"B1", topic:"weather", es:"Espero que haga sol el fin de semana.", en:"I hope it's sunny on the weekend."},
  {id:"dB1WEA07", lv:"B1", topic:"weather", es:"Con este tiempo, apetece quedarse en casa.", en:"In this weather, you feel like staying home."},
  {id:"dB1WEA08", lv:"B1", topic:"weather", es:"Nunca se sabe qué tiempo hará.", en:"You never know what the weather will be like."},
  {id:"dB1WEA09", lv:"B1", topic:"weather", es:"El clima está cada vez más loco.", en:"The weather is getting crazier and crazier."},
  {id:"dB1WEA10", lv:"B1", topic:"weather", es:"Si no fuera por la lluvia, iría a correr.", en:"If it weren't for the rain, I'd go running."},
  // social
  {id:"dB1SOC01", lv:"B1", topic:"social", es:"Me apetece hacer algo diferente.", en:"I feel like doing something different."},
  {id:"dB1SOC02", lv:"B1", topic:"social", es:"¿Qué planes tienes para el finde?", en:"What plans do you have for the weekend?"},
  {id:"dB1SOC03", lv:"B1", topic:"social", es:"Me da igual, lo que tú prefieras.", en:"I don't mind, whatever you prefer."},
  {id:"dB1SOC04", lv:"B1", topic:"social", es:"Hace tiempo que quería decírtelo.", en:"I've wanted to tell you for a while."},
  {id:"dB1SOC05", lv:"B1", topic:"social", es:"No me importaría repetirlo.", en:"I wouldn't mind doing it again."},
  {id:"dB1SOC06", lv:"B1", topic:"social", es:"Estaba deseando que llegara este día.", en:"I was looking forward to this day."},
  {id:"dB1SOC07", lv:"B1", topic:"social", es:"Cuenta conmigo para lo que sea.", en:"Count on me for anything."},
  {id:"dB1SOC08", lv:"B1", topic:"social", es:"Perdona si te he molestado.", en:"Sorry if I've bothered you."},
  {id:"dB1SOC09", lv:"B1", topic:"social", es:"Deberíamos celebrarlo.", en:"We should celebrate."},
  {id:"dB1SOC10", lv:"B1", topic:"social", es:"Aunque estoy cansada, me apunto.", en:"Although I'm tired, I'm in."},

  /* ===================== B2 ===================== */
  // greetings
  {id:"dB2GRE01", lv:"B2", topic:"greetings", es:"No esperaba encontrarte por aquí.", en:"I didn't expect to run into you here."},
  {id:"dB2GRE02", lv:"B2", topic:"greetings", es:"Tenía muchas ganas de conocerte en persona.", en:"I really wanted to meet you in person."},
  {id:"dB2GRE03", lv:"B2", topic:"greetings", es:"Se me hace raro que no nos hayamos visto antes.", en:"It's strange we haven't met before."},
  {id:"dB2GRE04", lv:"B2", topic:"greetings", es:"Me alegra un montón que hayas venido.", en:"I'm really glad you came."},
  {id:"dB2GRE05", lv:"B2", topic:"greetings", es:"Como te iba diciendo el otro día...", en:"As I was telling you the other day..."},
  {id:"dB2GRE06", lv:"B2", topic:"greetings", es:"No quisiera molestarte, pero...", en:"I wouldn't want to bother you, but..."},
  {id:"dB2GRE07", lv:"B2", topic:"greetings", es:"Hacía años que no coincidíamos.", en:"We hadn't crossed paths in years."},
  {id:"dB2GRE08", lv:"B2", topic:"greetings", es:"Me hace mucha ilusión verte.", en:"I'm really excited to see you."},
  {id:"dB2GRE09", lv:"B2", topic:"greetings", es:"Espero que no te importe que te escriba.", en:"I hope you don't mind me writing to you."},
  {id:"dB2GRE10", lv:"B2", topic:"greetings", es:"Disculpa, ¿nos conocemos de algo?", en:"Excuse me, do we know each other from somewhere?"},
  // family
  {id:"dB2FAM01", lv:"B2", topic:"family", es:"Por mucho que discutamos, siempre nos apoyamos.", en:"No matter how much we argue, we always support each other."},
  {id:"dB2FAM02", lv:"B2", topic:"family", es:"Ojalá hubiera pasado más tiempo con ellos.", en:"I wish I had spent more time with them."},
  {id:"dB2FAM03", lv:"B2", topic:"family", es:"A medida que crecen, se parecen más a su padre.", en:"As they grow, they look more like their father."},
  {id:"dB2FAM04", lv:"B2", topic:"family", es:"No es que no los quiera, es que necesito mi espacio.", en:"It's not that I don't love them, I just need my space."},
  {id:"dB2FAM05", lv:"B2", topic:"family", es:"Me habría gustado que estuvieran aquí.", en:"I would have liked them to be here."},
  {id:"dB2FAM06", lv:"B2", topic:"family", es:"Tener hijos te cambia la vida por completo.", en:"Having children changes your life completely."},
  {id:"dB2FAM07", lv:"B2", topic:"family", es:"Aunque estemos lejos, seguimos muy unidos.", en:"Even though we're far, we stay very close."},
  {id:"dB2FAM08", lv:"B2", topic:"family", es:"Con el tiempo, aprendes a valorar a la familia.", en:"Over time, you learn to value family."},
  {id:"dB2FAM09", lv:"B2", topic:"family", es:"Cueste lo que cueste, estaré para ellos.", en:"Whatever it takes, I'll be there for them."},
  {id:"dB2FAM10", lv:"B2", topic:"family", es:"Es como si nos entendiéramos sin hablar.", en:"It's as if we understand each other without speaking."},
  // food
  {id:"dB2FOO01", lv:"B2", topic:"food", es:"Por más que lo intento, no me sale la receta.", en:"However much I try, the recipe doesn't come out right."},
  {id:"dB2FOO02", lv:"B2", topic:"food", es:"Si no hubiéramos reservado, no habríamos entrado.", en:"If we hadn't booked, we wouldn't have gotten in."},
  {id:"dB2FOO03", lv:"B2", topic:"food", es:"No hay nada como una comida casera.", en:"There's nothing like a home-cooked meal."},
  {id:"dB2FOO04", lv:"B2", topic:"food", es:"Me da la impresión de que está un poco soso.", en:"I get the impression it's a bit bland."},
  {id:"dB2FOO05", lv:"B2", topic:"food", es:"Aunque parezca sencillo, cuesta hacerlo bien.", en:"Although it seems simple, it's hard to do well."},
  {id:"dB2FOO06", lv:"B2", topic:"food", es:"Te recomendaría que probaras el pescado.", en:"I'd recommend you try the fish."},
  {id:"dB2FOO07", lv:"B2", topic:"food", es:"Se nota que está hecho con productos frescos.", en:"You can tell it's made with fresh ingredients."},
  {id:"dB2FOO08", lv:"B2", topic:"food", es:"No sé qué tiene, pero está buenísimo.", en:"I don't know what it's got, but it's delicious."},
  {id:"dB2FOO09", lv:"B2", topic:"food", es:"La verdad es que se me ha quitado el apetito.", en:"Honestly, I've lost my appetite."},
  {id:"dB2FOO10", lv:"B2", topic:"food", es:"Como sigamos así, no cabremos por la puerta.", en:"If we keep this up, we won't fit through the door."},
  // shopping
  {id:"dB2SHO01", lv:"B2", topic:"shopping", es:"Por muy bonito que sea, no lo necesito.", en:"However nice it is, I don't need it."},
  {id:"dB2SHO02", lv:"B2", topic:"shopping", es:"De haberlo sabido, no lo habría comprado.", en:"Had I known, I wouldn't have bought it."},
  {id:"dB2SHO03", lv:"B2", topic:"shopping", es:"No es que sea caro, es que no me convence.", en:"It's not that it's expensive, it's that I'm not convinced."},
  {id:"dB2SHO04", lv:"B2", topic:"shopping", es:"Lo compraría si estuviera rebajado.", en:"I'd buy it if it were on sale."},
  {id:"dB2SHO05", lv:"B2", topic:"shopping", es:"Prefiero gastar en experiencias que en cosas.", en:"I prefer spending on experiences than things."},
  {id:"dB2SHO06", lv:"B2", topic:"shopping", es:"Como no me quede bien, lo devolveré.", en:"If it doesn't fit me, I'll return it."},
  {id:"dB2SHO07", lv:"B2", topic:"shopping", es:"Me ha costado un ojo de la cara.", en:"It cost me an arm and a leg."},
  {id:"dB2SHO08", lv:"B2", topic:"shopping", es:"Merece la pena esperar a las rebajas.", en:"It's worth waiting for the sales."},
  {id:"dB2SHO09", lv:"B2", topic:"shopping", es:"Me temo que se me ha ido de las manos el gasto.", en:"I'm afraid the spending got out of hand."},
  {id:"dB2SHO10", lv:"B2", topic:"shopping", es:"Se ve que es de buena calidad.", en:"You can see it's good quality."},
  // travel
  {id:"dB2TRA01", lv:"B2", topic:"travel", es:"De no ser por el mal tiempo, habría sido perfecto.", en:"If it weren't for the bad weather, it would have been perfect."},
  {id:"dB2TRA02", lv:"B2", topic:"travel", es:"Por más que planees, siempre surge algo.", en:"No matter how much you plan, something always comes up."},
  {id:"dB2TRA03", lv:"B2", topic:"travel", es:"Me habría gustado quedarme más tiempo.", en:"I would have liked to stay longer."},
  {id:"dB2TRA04", lv:"B2", topic:"travel", es:"En cuanto tenga vacaciones, me iré de viaje.", en:"As soon as I have holidays, I'll go on a trip."},
  {id:"dB2TRA05", lv:"B2", topic:"travel", es:"Nunca imaginé que fuera tan bonito.", en:"I never imagined it would be so beautiful."},
  {id:"dB2TRA06", lv:"B2", topic:"travel", es:"Si volviera a ir, cambiaría el hotel.", en:"If I went again, I'd change the hotel."},
  {id:"dB2TRA07", lv:"B2", topic:"travel", es:"Lo mejor del viaje fue la gente.", en:"The best part of the trip was the people."},
  {id:"dB2TRA08", lv:"B2", topic:"travel", es:"Viajar te abre la mente.", en:"Traveling broadens your mind."},
  {id:"dB2TRA09", lv:"B2", topic:"travel", es:"Como no reservemos ya, nos quedaremos sin sitio.", en:"If we don't book now, we'll be left without a spot."},
  {id:"dB2TRA10", lv:"B2", topic:"travel", es:"Aunque sea caro, el viaje vale la pena.", en:"Even if it's expensive, the trip is worth it."},
  // routine
  {id:"dB2ROU01", lv:"B2", topic:"routine", es:"Por mucho que madrugue, nunca me da tiempo.", en:"However early I get up, I never have enough time."},
  {id:"dB2ROU02", lv:"B2", topic:"routine", es:"Últimamente ando bastante liada.", en:"Lately I've been quite busy."},
  {id:"dB2ROU03", lv:"B2", topic:"routine", es:"Debería organizarme mejor, la verdad.", en:"I really should organize myself better."},
  {id:"dB2ROU04", lv:"B2", topic:"routine", es:"En cuanto tenga un hueco, te llamo.", en:"As soon as I have a gap, I'll call you."},
  {id:"dB2ROU05", lv:"B2", topic:"routine", es:"Si no fuera por el café, no funcionaría.", en:"If it weren't for coffee, I wouldn't function."},
  {id:"dB2ROU06", lv:"B2", topic:"routine", es:"Me he propuesto cuidarme más este año.", en:"I've resolved to take better care of myself this year."},
  {id:"dB2ROU07", lv:"B2", topic:"routine", es:"Aunque esté cansada, no consigo dormirme.", en:"Even though I'm tired, I can't fall asleep."},
  {id:"dB2ROU08", lv:"B2", topic:"routine", es:"Cada vez me cuesta más desconectar.", en:"It's getting harder and harder to switch off."},
  {id:"dB2ROU09", lv:"B2", topic:"routine", es:"Ojalá los días tuvieran más horas.", en:"I wish the days had more hours."},
  {id:"dB2ROU10", lv:"B2", topic:"routine", es:"Como no cambie de hábitos, seguiré igual.", en:"If I don't change my habits, I'll stay the same."},
  // health
  {id:"dB2HEA01", lv:"B2", topic:"health", es:"Más vale prevenir que curar.", en:"Better safe than sorry."},
  {id:"dB2HEA02", lv:"B2", topic:"health", es:"El médico insiste en que reduzca el estrés.", en:"The doctor insists that I reduce stress."},
  {id:"dB2HEA03", lv:"B2", topic:"health", es:"Por más que descanse, sigo agotada.", en:"However much I rest, I'm still exhausted."},
  {id:"dB2HEA04", lv:"B2", topic:"health", es:"No es que esté mal, es que estoy baja de energía.", en:"It's not that I'm ill, I'm just low on energy."},
  {id:"dB2HEA05", lv:"B2", topic:"health", es:"Como no cambie de dieta, no mejoraré.", en:"If I don't change my diet, I won't improve."},
  {id:"dB2HEA06", lv:"B2", topic:"health", es:"Me recomendaron que hiciera más ejercicio.", en:"They recommended I exercise more."},
  {id:"dB2HEA07", lv:"B2", topic:"health", es:"Espero que los resultados salgan bien.", en:"I hope the results come out fine."},
  {id:"dB2HEA08", lv:"B2", topic:"health", es:"Con la edad, hay que cuidarse más.", en:"With age, you have to take more care."},
  {id:"dB2HEA09", lv:"B2", topic:"health", es:"Ojalá me hubiera hecho el chequeo antes.", en:"I wish I'd had the check-up sooner."},
  {id:"dB2HEA10", lv:"B2", topic:"health", es:"De haberme cuidado antes, no estaría así.", en:"Had I taken care of myself earlier, I wouldn't be like this."},
  // work
  {id:"dB2WOR01", lv:"B2", topic:"work", es:"Por muy bien que lo haga, nunca es suficiente.", en:"However well I do it, it's never enough."},
  {id:"dB2WOR02", lv:"B2", topic:"work", es:"De seguir así, acabaré quemada.", en:"If this continues, I'll end up burnt out."},
  {id:"dB2WOR03", lv:"B2", topic:"work", es:"Me plantearía cambiar de sector.", en:"I'd consider changing sectors."},
  {id:"dB2WOR04", lv:"B2", topic:"work", es:"En cuanto termine este proyecto, pediré vacaciones.", en:"As soon as I finish this project, I'll ask for holidays."},
  {id:"dB2WOR05", lv:"B2", topic:"work", es:"Aunque cueste, hay que saber decir que no.", en:"Even if it's hard, you have to know how to say no."},
  {id:"dB2WOR06", lv:"B2", topic:"work", es:"Me han ofrecido un puesto mejor.", en:"I've been offered a better position."},
  {id:"dB2WOR07", lv:"B2", topic:"work", es:"Ojalá hubiera estudiado otra cosa.", en:"I wish I'd studied something else."},
  {id:"dB2WOR08", lv:"B2", topic:"work", es:"Lo importante es disfrutar de lo que haces.", en:"The important thing is to enjoy what you do."},
  {id:"dB2WOR09", lv:"B2", topic:"work", es:"Como no me valoren, buscaré otra cosa.", en:"If they don't value me, I'll look for something else."},
  {id:"dB2WOR10", lv:"B2", topic:"work", es:"No es que no me guste, es que necesito un cambio.", en:"It's not that I don't like it, I just need a change."},
  // weather
  {id:"dB2WEA01", lv:"B2", topic:"weather", es:"Por mucho frío que haga, salgo a caminar.", en:"However cold it is, I go out for a walk."},
  {id:"dB2WEA02", lv:"B2", topic:"weather", es:"De haber sabido que llovería, habría cogido el paraguas.", en:"Had I known it would rain, I'd have taken the umbrella."},
  {id:"dB2WEA03", lv:"B2", topic:"weather", es:"El tiempo está de lo más impredecible.", en:"The weather is extremely unpredictable."},
  {id:"dB2WEA04", lv:"B2", topic:"weather", es:"Como siga lloviendo, se inundará todo.", en:"If it keeps raining, everything will flood."},
  {id:"dB2WEA05", lv:"B2", topic:"weather", es:"No es que haga frío, es que hay mucha humedad.", en:"It's not that it's cold, it's that it's very humid."},
  {id:"dB2WEA06", lv:"B2", topic:"weather", es:"En cuanto salga el sol, iremos a la playa.", en:"As soon as the sun comes out, we'll go to the beach."},
  {id:"dB2WEA07", lv:"B2", topic:"weather", es:"Aunque haga viento, merece la pena el paseo.", en:"Even if it's windy, the walk is worth it."},
  {id:"dB2WEA08", lv:"B2", topic:"weather", es:"Este año el invierno se está alargando.", en:"This year the winter is dragging on."},
  {id:"dB2WEA09", lv:"B2", topic:"weather", es:"Con el cambio climático, ya no hay estaciones.", en:"With climate change, there are no seasons anymore."},
  {id:"dB2WEA10", lv:"B2", topic:"weather", es:"Ojalá hiciera mejor tiempo.", en:"I wish the weather were better."},
  // social
  {id:"dB2SOC01", lv:"B2", topic:"social", es:"Por más que lo pienso, no sé qué decidir.", en:"However much I think about it, I don't know what to decide."},
  {id:"dB2SOC02", lv:"B2", topic:"social", es:"De haberlo sabido, te habría avisado.", en:"Had I known, I'd have let you know."},
  {id:"dB2SOC03", lv:"B2", topic:"social", es:"No es que no quiera ir, es que estoy sin energía.", en:"It's not that I don't want to go, I'm just out of energy."},
  {id:"dB2SOC04", lv:"B2", topic:"social", es:"En cuanto me lo confirmes, reservo.", en:"As soon as you confirm, I'll book."},
  {id:"dB2SOC05", lv:"B2", topic:"social", es:"Aunque me lo pidieras, no podría.", en:"Even if you asked me, I couldn't."},
  {id:"dB2SOC06", lv:"B2", topic:"social", es:"Me hace mucha ilusión que vengas.", en:"I'm really excited that you're coming."},
  {id:"dB2SOC07", lv:"B2", topic:"social", es:"Ojalá pudiéramos vernos más a menudo.", en:"I wish we could see each other more often."},
  {id:"dB2SOC08", lv:"B2", topic:"social", es:"Te agradezco un montón el detalle.", en:"I really appreciate the gesture."},
  {id:"dB2SOC09", lv:"B2", topic:"social", es:"Cuenta conmigo para lo que necesites.", en:"Count on me for whatever you need."},
  {id:"dB2SOC10", lv:"B2", topic:"social", es:"Como no me avises, no me entero.", en:"If you don't tell me, I won't know."}
];
const DRILL_BY_ID = Object.fromEntries(DRILLS.map(d => [d.id, d]));
