// Hands-free speaking drills, graded A1 → B2.
// es = target sentence, en = English meaning/cue. lv = level band.
// A1/A2 show the Spanish (read & repeat); B1/B2 hide it (produce from English).
const DRILLS = [
  // ---------- A1 ----------
  {id:"d001", lv:"A1", es:"Hola, ¿cómo estás?", en:"Hello, how are you?"},
  {id:"d002", lv:"A1", es:"Me llamo Ana.", en:"My name is Ana."},
  {id:"d003", lv:"A1", es:"Soy de Holanda.", en:"I am from Holland."},
  {id:"d004", lv:"A1", es:"Muchas gracias.", en:"Thank you very much."},
  {id:"d005", lv:"A1", es:"¿Dónde está el baño?", en:"Where is the bathroom?"},
  {id:"d006", lv:"A1", es:"Quiero un café, por favor.", en:"I want a coffee, please."},
  {id:"d007", lv:"A1", es:"No entiendo.", en:"I don't understand."},
  {id:"d008", lv:"A1", es:"¿Hablas inglés?", en:"Do you speak English?"},
  {id:"d009", lv:"A1", es:"Hoy hace buen tiempo.", en:"Today the weather is nice."},
  {id:"d010", lv:"A1", es:"Tengo dos hermanos.", en:"I have two brothers."},
  {id:"d011", lv:"A1", es:"Me gusta la música.", en:"I like music."},
  {id:"d012", lv:"A1", es:"¿Qué hora es?", en:"What time is it?"},
  {id:"d013", lv:"A1", es:"La cuenta, por favor.", en:"The bill, please."},
  {id:"d014", lv:"A1", es:"Hasta mañana.", en:"See you tomorrow."},
  {id:"d015", lv:"A1", es:"Estoy cansado hoy.", en:"I am tired today."},

  // ---------- A2 ----------
  {id:"d016", lv:"A2", es:"Ayer fui al mercado.", en:"Yesterday I went to the market."},
  {id:"d017", lv:"A2", es:"Voy a viajar a España.", en:"I am going to travel to Spain."},
  {id:"d018", lv:"A2", es:"¿Puedes ayudarme, por favor?", en:"Can you help me, please?"},
  {id:"d019", lv:"A2", es:"Me gustaría reservar una mesa.", en:"I would like to book a table."},
  {id:"d020", lv:"A2", es:"¿Cuánto cuesta esto?", en:"How much does this cost?"},
  {id:"d021", lv:"A2", es:"No me gusta el pescado.", en:"I don't like fish."},
  {id:"d022", lv:"A2", es:"Necesito ir al médico.", en:"I need to go to the doctor."},
  {id:"d023", lv:"A2", es:"¿A qué hora sale el tren?", en:"What time does the train leave?"},
  {id:"d024", lv:"A2", es:"Mi casa está cerca de la playa.", en:"My house is near the beach."},
  {id:"d025", lv:"A2", es:"Normalmente me levanto a las siete.", en:"I usually get up at seven."},
  {id:"d026", lv:"A2", es:"El fin de semana visito a mi familia.", en:"On the weekend I visit my family."},
  {id:"d027", lv:"A2", es:"¿Puedo pagar con tarjeta?", en:"Can I pay by card?"},
  {id:"d028", lv:"A2", es:"Hace mucho calor en verano.", en:"It's very hot in summer."},
  {id:"d029", lv:"A2", es:"Estoy aprendiendo español.", en:"I am learning Spanish."},
  {id:"d030", lv:"A2", es:"¿Qué me recomiendas?", en:"What do you recommend?"},

  // ---------- B1 ----------
  {id:"d031", lv:"B1", es:"Creo que tienes razón.", en:"I think you are right."},
  {id:"d032", lv:"B1", es:"Cuando era niño, vivía en el campo.", en:"When I was a child, I lived in the countryside."},
  {id:"d033", lv:"B1", es:"Si tengo tiempo, iré al cine.", en:"If I have time, I will go to the cinema."},
  {id:"d034", lv:"B1", es:"Me alegro de que estés aquí.", en:"I'm glad you are here."},
  {id:"d035", lv:"B1", es:"Aunque llueve, quiero salir.", en:"Although it's raining, I want to go out."},
  {id:"d036", lv:"B1", es:"He estado muy ocupado esta semana.", en:"I have been very busy this week."},
  {id:"d037", lv:"B1", es:"Espero que todo salga bien.", en:"I hope everything goes well."},
  {id:"d038", lv:"B1", es:"No estoy seguro de lo que quiero.", en:"I'm not sure what I want."},
  {id:"d039", lv:"B1", es:"Antes de dormir, leo un libro.", en:"Before sleeping, I read a book."},
  {id:"d040", lv:"B1", es:"Me parece que va a llover.", en:"It seems to me it's going to rain."},
  {id:"d041", lv:"B1", es:"Es importante hacer ejercicio.", en:"It's important to exercise."},
  {id:"d042", lv:"B1", es:"Aprender un idioma requiere paciencia.", en:"Learning a language requires patience."},
  {id:"d043", lv:"B1", es:"Prefiero quedarme en casa esta noche.", en:"I prefer to stay home tonight."},
  {id:"d044", lv:"B1", es:"¿Podrías repetir eso más despacio?", en:"Could you repeat that more slowly?"},
  {id:"d045", lv:"B1", es:"Todavía no he terminado el trabajo.", en:"I still haven't finished the work."},

  // ---------- B2 ----------
  {id:"d046", lv:"B2", es:"Si hubiera sabido, habría venido antes.", en:"If I had known, I would have come earlier."},
  {id:"d047", lv:"B2", es:"Aunque esté cansada, terminaré el proyecto.", en:"Even if I'm tired, I'll finish the project."},
  {id:"d048", lv:"B2", es:"Me habría gustado que me lo dijeras.", en:"I would have liked you to tell me."},
  {id:"d049", lv:"B2", es:"No creo que sea una buena idea.", en:"I don't think it's a good idea."},
  {id:"d050", lv:"B2", es:"En cuanto llegue, te llamaré.", en:"As soon as I arrive, I'll call you."},
  {id:"d051", lv:"B2", es:"A pesar de las dificultades, seguimos adelante.", en:"Despite the difficulties, we carry on."},
  {id:"d052", lv:"B2", es:"Lo que más me preocupa es el tiempo.", en:"What worries me most is the time."},
  {id:"d053", lv:"B2", es:"Ojalá pudiera viajar más a menudo.", en:"I wish I could travel more often."},
  {id:"d054", lv:"B2", es:"Por mucho que lo intente, no lo consigo.", en:"No matter how much I try, I can't manage it."},
  {id:"d055", lv:"B2", es:"Deberíamos haber reservado con antelación.", en:"We should have booked in advance."},
  {id:"d056", lv:"B2", es:"Me da la impresión de que algo no va bien.", en:"I get the impression that something is wrong."},
  {id:"d057", lv:"B2", es:"Cuanto más practico, más confianza tengo.", en:"The more I practice, the more confidence I have."},
  {id:"d058", lv:"B2", es:"Si fuera tú, hablaría con ella.", en:"If I were you, I would talk to her."},
  {id:"d059", lv:"B2", es:"No vale la pena preocuparse por eso.", en:"It's not worth worrying about that."},
  {id:"d060", lv:"B2", es:"Espero que hayas disfrutado de tu viaje.", en:"I hope you enjoyed your trip."},

  // ---------- A1 (more) ----------
  {id:"d061", lv:"A1", es:"Buenos días.", en:"Good morning."},
  {id:"d062", lv:"A1", es:"Buenas tardes.", en:"Good afternoon."},
  {id:"d063", lv:"A1", es:"¿De dónde eres?", en:"Where are you from?"},
  {id:"d064", lv:"A1", es:"Soy de los Países Bajos.", en:"I'm from the Netherlands."},
  {id:"d065", lv:"A1", es:"Hablo un poco de español.", en:"I speak a little Spanish."},
  {id:"d066", lv:"A1", es:"¿Cómo te llamas?", en:"What's your name?"},
  {id:"d067", lv:"A1", es:"Tengo hambre.", en:"I'm hungry."},
  {id:"d068", lv:"A1", es:"Tengo sed.", en:"I'm thirsty."},
  {id:"d069", lv:"A1", es:"¿Cuánto es?", en:"How much is it?"},
  {id:"d070", lv:"A1", es:"Está bien.", en:"It's fine."},
  {id:"d071", lv:"A1", es:"Me gusta el café.", en:"I like coffee."},
  {id:"d072", lv:"A1", es:"¿Qué es esto?", en:"What is this?"},
  {id:"d073", lv:"A1", es:"No sé.", en:"I don't know."},
  {id:"d074", lv:"A1", es:"Un momento, por favor.", en:"One moment, please."},
  {id:"d075", lv:"A1", es:"Hasta luego.", en:"See you later."},

  // ---------- A2 (more) ----------
  {id:"d076", lv:"A2", es:"¿Puede repetir, por favor?", en:"Can you repeat, please?"},
  {id:"d077", lv:"A2", es:"No estoy seguro.", en:"I'm not sure."},
  {id:"d078", lv:"A2", es:"¿Dónde puedo comprar agua?", en:"Where can I buy water?"},
  {id:"d079", lv:"A2", es:"Quisiera una habitación.", en:"I'd like a room."},
  {id:"d080", lv:"A2", es:"¿Está incluido el desayuno?", en:"Is breakfast included?"},
  {id:"d081", lv:"A2", es:"Voy a pagar en efectivo.", en:"I'll pay in cash."},
  {id:"d082", lv:"A2", es:"¿Hay wifi aquí?", en:"Is there wifi here?"},
  {id:"d083", lv:"A2", es:"Estoy buscando la estación.", en:"I'm looking for the station."},
  {id:"d084", lv:"A2", es:"Me duele la cabeza.", en:"I have a headache."},
  {id:"d085", lv:"A2", es:"¿A qué hora abre?", en:"What time does it open?"},
  {id:"d086", lv:"A2", es:"Prefiero el té.", en:"I prefer tea."},
  {id:"d087", lv:"A2", es:"Tenemos una reserva.", en:"We have a reservation."},
  {id:"d088", lv:"A2", es:"¿Cuál me recomienda?", en:"Which do you recommend?"},
  {id:"d089", lv:"A2", es:"Está muy rico.", en:"It's very tasty."},
  {id:"d090", lv:"A2", es:"¿Puede ayudarme, por favor?", en:"Can you help me, please?"},

  // ---------- B1 (more) ----------
  {id:"d091", lv:"B1", es:"¿Podría hablar más despacio?", en:"Could you speak more slowly?"},
  {id:"d092", lv:"B1", es:"No entendí bien.", en:"I didn't understand well."},
  {id:"d093", lv:"B1", es:"¿Qué te parece si vamos al cine?", en:"How about we go to the cinema?"},
  {id:"d094", lv:"B1", es:"Estoy de acuerdo contigo.", en:"I agree with you."},
  {id:"d095", lv:"B1", es:"Depende del tiempo.", en:"It depends on the weather."},
  {id:"d096", lv:"B1", es:"Me encantaría, pero no puedo.", en:"I'd love to, but I can't."},
  {id:"d097", lv:"B1", es:"¿Has estado alguna vez en España?", en:"Have you ever been to Spain?"},
  {id:"d098", lv:"B1", es:"Todavía estoy aprendiendo.", en:"I'm still learning."},
  {id:"d099", lv:"B1", es:"¿Te importa si abro la ventana?", en:"Do you mind if I open the window?"},
  {id:"d100", lv:"B1", es:"Llevo dos años estudiando español.", en:"I've been studying Spanish for two years."},
  {id:"d101", lv:"B1", es:"Quedamos a las ocho.", en:"Let's meet at eight."},
  {id:"d102", lv:"B1", es:"No vale la pena.", en:"It's not worth it."},
  {id:"d103", lv:"B1", es:"Me lo estoy pasando muy bien.", en:"I'm having a great time."},
  {id:"d104", lv:"B1", es:"Cada vez lo entiendo mejor.", en:"I understand it better each time."},
  {id:"d105", lv:"B1", es:"¿Me puedes dar un consejo?", en:"Can you give me some advice?"},

  // ---------- B2 (more) ----------
  {id:"d106", lv:"B2", es:"Si tuviera más tiempo, viajaría más.", en:"If I had more time, I'd travel more."},
  {id:"d107", lv:"B2", es:"Aunque sea difícil, quiero intentarlo.", en:"Even if it's hard, I want to try."},
  {id:"d108", lv:"B2", es:"Me gustaría que vinieras conmigo.", en:"I'd like you to come with me."},
  {id:"d109", lv:"B2", es:"No creo que valga la pena discutir.", en:"I don't think it's worth arguing."},
  {id:"d110", lv:"B2", es:"Tan pronto como termine, te aviso.", en:"As soon as I finish, I'll let you know."},
  {id:"d111", lv:"B2", es:"Por más que estudio, siempre hay más.", en:"However much I study, there's always more."},
  {id:"d112", lv:"B2", es:"Habría venido si me hubieras llamado.", en:"I would have come if you'd called me."},
  {id:"d113", lv:"B2", es:"Lo que necesito es más práctica.", en:"What I need is more practice."},
  {id:"d114", lv:"B2", es:"Supongo que tienes razón.", en:"I suppose you're right."},
  {id:"d115", lv:"B2", es:"A medida que pasa el tiempo, mejoro.", en:"As time passes, I improve."},
  {id:"d116", lv:"B2", es:"No es que no quiera, es que no puedo.", en:"It's not that I don't want to, it's that I can't."},
  {id:"d117", lv:"B2", es:"Ojalá hubiera empezado antes.", en:"I wish I had started earlier."},
  {id:"d118", lv:"B2", es:"Vale la pena el esfuerzo.", en:"It's worth the effort."},
  {id:"d119", lv:"B2", es:"Cuanto antes, mejor.", en:"The sooner, the better."},
  {id:"d120", lv:"B2", es:"Me da igual, tú decides.", en:"I don't mind, you decide."}
];
const DRILL_BY_ID = Object.fromEntries(DRILLS.map(d => [d.id, d]));
